#pragma config(Sensor, in5,    centerLight,    sensorAnalog)
#pragma config(Sensor, in6,    backLight,      sensorAnalog)
#pragma config(Sensor, in7,    frontUpperLight, sensorAnalog)
#pragma config(Sensor, in8,    frontBelowLight, sensorAnalog)
#pragma config(Sensor, dgtl1,  unusedD1,       sensorNone)
#pragma config(Sensor, dgtl2,  unusedD2,       sensorNone)
#pragma config(Sensor, dgtl3,  west,           sensorDigitalIn)
#pragma config(Sensor, dgtl4,  south,          sensorDigitalIn)
#pragma config(Sensor, dgtl5,  east,           sensorDigitalIn)
#pragma config(Sensor, dgtl6,  north,          sensorDigitalIn)
#pragma config(Sensor, dgtl7,  gateEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  backRightLine,  sensorDigitalIn)
#pragma config(Sensor, dgtl10, backLeftLine,   sensorDigitalIn)
#pragma config(Sensor, dgtl11, frontRightLine, sensorDigitalIn)
#pragma config(Sensor, dgtl12, frontLeftLine,  sensorDigitalIn)
#pragma config(Motor,  port6,           gateMotor,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           collectorMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightWheel,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftWheel,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// -------------------------
// Searching phase constants
// -------------------------
const int FRONT_LOWER_BALL_MIN = 1000;
const int FRONT_UPPER_BALL_MAX = 700;
const int SEARCH_FORWARD_MS = 1000;
const int SEARCH_PRE_ALIGN_SCAN_MS = 2000;
const int SEARCH_ALIGN_TURN_POWER = 45;
const int SEARCH_ALIGN_REVERSE_MS = 50;
const int SEARCH_MAX_CYCLES = 3;
const int SEARCH_ALIGN_TIMEOUT_MS = 5000;
const int BALL_CONFIRM_SAMPLES = 5;
const int BALL_DELTA_MIN = 500;
const int UPPER_SAFETY_BLOCK_MIN = 1800;
const int SEARCH_SAFETY_REVERSE_MS = 700;
const int SEARCH_SAFETY_REVERSE_POWER = 100;
const int DRIVE_FORWARD_POWER = 85;
const int SEARCH_COLLECTOR_POWER = 127;

const int SEARCH_RESULT_NO_BALL = 0;
const int SEARCH_RESULT_BALL_FOUND = 1;

// -------------------------
// Collecting phase constants
// -------------------------
const int CENTER_BALL_COLLECT_MIN = 1300;
const int COLLECT_TIMEOUT_MS = 1000;
const int COLLECT_EXTRA_SPIN_TIMEOUT_MS = 5000;
const int DRIVE_COLLECT_POWER = 90;
const int COLLECT_PRE_TURN_POWER = 45;
const int COLLECT_PRE_TURN_MS = 200;
const int COLLECTOR_POWER = 200;

const int COLLECT_RESULT_TIMEOUT = 0;
const int COLLECT_RESULT_SUCCESS = 1;

// -------------------------
// Depositing phase constants
// -------------------------
const int BACK_SENSOR_DONE_MIN        = 2500;
const int DEPOSIT_ALIGN_TIMEOUT_MS    = 5000;
const int DEPOSIT_INITIAL_REVERSE_MS  = 3000;
const int DEPOSIT_STEP_REVERSE_MS     = 1000;
const int DEPOSIT_TIMEOUT_MS          = 10000;
const int DRIVE_REVERSE_LEFT_POWER    = 80;
const int DRIVE_REVERSE_RIGHT_POWER   = 60;
const int DRIVE_TURN_POWER            = 60;

const int GATE_ENCODER_TARGET = 90;
const int GATE_ENCODER_POST_TARGET = 0;
const int GATE_MIN_POWER = 35;
const int GATE_MAX_POWER = 80;
const int GATE_OPEN_HOLD_MS = 5000;
const float GATE_PD_KP = 0.56;
const float GATE_PD_KD = 0.35;

const int DEPOSIT_RESULT_TIMEOUT = 0;
const int DEPOSIT_RESULT_STABLE = 1;

// -------------------------
// Transition constants
// -------------------------
const int PHASE_TRANSITION_DELAY_MS = 0;

// -------------------------
// Boundary safety constants (always-on across all phases)
// -------------------------
const int floorValue = 0;
const int boundaryValue = 1;
const int BOUNDARY_RECOVERY_POWER = 53;
const int BOUNDARY_FRONT_RECOVERY_MS = 500;
const int BOUNDARY_BACK_RECOVERY_MS = 500;
const int BOUNDARY_ALIGN_TURN_POWER = 55;
const int BOUNDARY_ALIGN_STABLE_SAMPLES = 3;

const int BOUNDARY_TRIGGER_NONE = 0;
const int BOUNDARY_TRIGGER_FRONT = 1;
const int BOUNDARY_TRIGGER_BACK = 2;
const int BOUNDARY_TRIGGER_BOTH = 3;

// -------------------------
// Shared state
// -------------------------
int searchLowerTriggered = 0;
int searchLowerPeak = 0;
int searchLowerSum = 0;
int searchLowerSamples = 0;
int depositSequenceHasRun = 0;
int searchCenterDetected = 0;
int boundaryRecoveryActive = 0;

int isBallCollectedAtCenter();
int checkAndHandleBoundaryRecovery();
void waitWithBoundaryCheck(int durationMs);

void setDrive(int leftPower, int rightPower) {
  motor[leftWheel] = leftPower;
  motor[rightWheel] = rightPower;
}

void stopDrive() {
  setDrive(0, 0);
}

void turnLeftInPlace(int power) {
  setDrive(-power, power);
}

void reverseStraight(int power) {
  setDrive(-power, -power);
}

int isBoundaryLine(int sensorValue) {
  return (sensorValue == boundaryValue);
}

int frontBoundaryDetected() {
  return (isBoundaryLine(SensorValue[frontLeftLine]) ||
          isBoundaryLine(SensorValue[frontRightLine]));
}

int backBoundaryDetected() {
  return (isBoundaryLine(SensorValue[backLeftLine]) ||
          isBoundaryLine(SensorValue[backRightLine]));
}

int detectBoundaryTrigger() {
  int frontTriggered = frontBoundaryDetected();
  int backTriggered = backBoundaryDetected();

  if (frontTriggered && backTriggered) return BOUNDARY_TRIGGER_BOTH;
  if (frontTriggered) return BOUNDARY_TRIGGER_FRONT;
  if (backTriggered) return BOUNDARY_TRIGGER_BACK;
  return BOUNDARY_TRIGGER_NONE;
}

int isEastAlignedExact() {
  return (SensorValue[east] == 0 &&
          SensorValue[north] == 1 &&
          SensorValue[south] == 1 &&
          SensorValue[west] == 1);
}

void alignToEastForBoundaryRecovery() {
  int stableCount = 0;

  while (stableCount < BOUNDARY_ALIGN_STABLE_SAMPLES) {
    if (isEastAlignedExact()) {
      stableCount++;
      stopDrive();
      wait1Msec(20);
      continue;
    }

    stableCount = 0;
    setDrive(BOUNDARY_ALIGN_TURN_POWER, -BOUNDARY_ALIGN_TURN_POWER);
    wait1Msec(25);
  }

  stopDrive();
  wait1Msec(80);
}

void recoverFromBoundary(int triggerSource) {
  boundaryRecoveryActive = 1;

  // Pure straight recovery only, then align to EAST.
  stopDrive();
  wait1Msec(40);

  if (triggerSource == BOUNDARY_TRIGGER_BACK) {
    setDrive(BOUNDARY_RECOVERY_POWER, BOUNDARY_RECOVERY_POWER);
    wait1Msec(BOUNDARY_BACK_RECOVERY_MS);
  } else {
    setDrive(-BOUNDARY_RECOVERY_POWER, -BOUNDARY_RECOVERY_POWER);
    wait1Msec(BOUNDARY_FRONT_RECOVERY_MS);
  }

  stopDrive();
  wait1Msec(80);
  alignToEastForBoundaryRecovery();
  boundaryRecoveryActive = 0;
}

int checkAndHandleBoundaryRecovery() {
  int trigger = BOUNDARY_TRIGGER_NONE;

  if (boundaryRecoveryActive) {
    return 0;
  }

  trigger = detectBoundaryTrigger();
  if (trigger == BOUNDARY_TRIGGER_NONE) {
    return 0;
  }

  writeDebugStreamLine(
    "BOUNDARY trigger=%d FL=%d FR=%d BL=%d BR=%d -> recovery",
    trigger,
    SensorValue[frontLeftLine],
    SensorValue[frontRightLine],
    SensorValue[backLeftLine],
    SensorValue[backRightLine]
  );
  recoverFromBoundary(trigger);
  return 1;
}

void waitWithBoundaryCheck(int durationMs) {
  int remaining = durationMs;

  while (remaining > 0) {
    checkAndHandleBoundaryRecovery();
    {
      int waitStep = (remaining > 10) ? 10 : remaining;
      wait1Msec(waitStep);
      remaining -= waitStep;
    }
  }
}

// -------------------------
// Searching phase
// -------------------------
int isBallCandidate() {
  int lower = SensorValue[frontBelowLight];
  int upper = SensorValue[frontUpperLight];

  return (lower > FRONT_LOWER_BALL_MIN &&
          upper < FRONT_UPPER_BALL_MAX &&
          (lower - upper) >= BALL_DELTA_MIN);
}

int isFrontLowerTriggered() {
  return SensorValue[frontBelowLight] > FRONT_LOWER_BALL_MIN;
}

int isFacingWest() {
  return (SensorValue[west] == 1 &&
          SensorValue[south] == 1 &&
          SensorValue[east] == 0 &&
          SensorValue[north] == 1);
}

void resetSearchLowerTracking() {
  searchLowerTriggered = 0;
  searchLowerPeak = 0;
  searchLowerSum = 0;
  searchLowerSamples = 0;
}

void updateSearchLowerTracking() {
  int lower = SensorValue[frontBelowLight];
  if (lower > searchLowerPeak) searchLowerPeak = lower;
  searchLowerSum += lower;
  searchLowerSamples++;
  if (isFrontLowerTriggered()) searchLowerTriggered = 1;
}

int handleUpperSafetyReverse() {
  if (SensorValue[frontUpperLight] <= UPPER_SAFETY_BLOCK_MIN) {
    return 0;
  }

  writeDebugStreamLine(
    "SEARCH safety reverse: upper=%d (> %d)",
    SensorValue[frontUpperLight],
    UPPER_SAFETY_BLOCK_MIN
  );
  reverseStraight(SEARCH_SAFETY_REVERSE_POWER);
  waitWithBoundaryCheck(SEARCH_SAFETY_REVERSE_MS);
  stopDrive();
  return 1;
}

int runForwardAndCheckBall(int durationMs) {
  int startTime = nSysTime;
  int ballConfirmCount = 0;

  while ((nSysTime - startTime) < durationMs) {
    if (isBallCollectedAtCenter()) {
      searchCenterDetected = 1;
      stopDrive();
      writeDebugStreamLine("SEARCH noticed center sensor ball capture.");
      return 1;
    }

    updateSearchLowerTracking();

    if (handleUpperSafetyReverse()) {
      ballConfirmCount = 0;
      continue;
    }

    if (isBallCandidate()) {
      ballConfirmCount++;
      if (ballConfirmCount >= BALL_CONFIRM_SAMPLES) {
        stopDrive();
        return 1;
      }
    } else {
      ballConfirmCount = 0;
    }

    setDrive(DRIVE_FORWARD_POWER, DRIVE_FORWARD_POWER);
    waitWithBoundaryCheck(20);
  }

  stopDrive();
  return 0;
}

int rotateCCWForScanAndCheckBall(int durationMs) {
  int startTime = nSysTime;
  int ballConfirmCount = 0;

  while ((nSysTime - startTime) < durationMs) {
    if (isBallCollectedAtCenter()) {
      searchCenterDetected = 1;
      stopDrive();
      writeDebugStreamLine("SEARCH noticed center sensor ball capture.");
      return 1;
    }

    updateSearchLowerTracking();

    if (handleUpperSafetyReverse()) {
      ballConfirmCount = 0;
      continue;
    }

    if (isBallCandidate()) {
      ballConfirmCount++;
      if (ballConfirmCount >= BALL_CONFIRM_SAMPLES) {
        stopDrive();
        return 1;
      }
    } else {
      ballConfirmCount = 0;
    }

    turnLeftInPlace(SEARCH_ALIGN_TURN_POWER);
    waitWithBoundaryCheck(20);
  }

  stopDrive();
  return 0;
}

int rotateCCWToWestAndCheckBall(int timeoutMs) {
  int startTime = nSysTime;
  int ballConfirmCount = 0;

  while ((nSysTime - startTime) < timeoutMs) {
    if (isBallCollectedAtCenter()) {
      searchCenterDetected = 1;
      stopDrive();
      writeDebugStreamLine("SEARCH noticed center sensor ball capture.");
      return 1;
    }

    updateSearchLowerTracking();

    if (handleUpperSafetyReverse()) {
      ballConfirmCount = 0;
      continue;
    }

    if (isBallCandidate()) {
      ballConfirmCount++;
      if (ballConfirmCount >= BALL_CONFIRM_SAMPLES) {
        stopDrive();
        return 1;
      }
    } else {
      ballConfirmCount = 0;
    }

    if (isFacingWest()) {
      setDrive(-SEARCH_ALIGN_TURN_POWER, SEARCH_ALIGN_TURN_POWER);
      waitWithBoundaryCheck(SEARCH_ALIGN_REVERSE_MS);
      stopDrive();
      return 0;
    }

    turnLeftInPlace(SEARCH_ALIGN_TURN_POWER);
    waitWithBoundaryCheck(10);
  }

  stopDrive();
  return 0;
}

int runSearchingPhase() {
  int cycle = 0;
  searchCenterDetected = 0;

  writeDebugStreamLine("SEARCH phase started (one-shot, max %d cycles).", SEARCH_MAX_CYCLES);

  for (cycle = 0; cycle < SEARCH_MAX_CYCLES; cycle++) {
    if (isBallCollectedAtCenter()) {
      searchCenterDetected = 1;
      stopDrive();
      writeDebugStreamLine("SEARCH immediate center sensor detection.");
      return SEARCH_RESULT_BALL_FOUND;
    }

    resetSearchLowerTracking();
    writeDebugStreamLine("SEARCH cycle %d/%d", cycle + 1, SEARCH_MAX_CYCLES);

    if (runForwardAndCheckBall(SEARCH_FORWARD_MS)) {
      writeDebugStreamLine("Ball detected during forward search.");
      return SEARCH_RESULT_BALL_FOUND;
    }

    if (rotateCCWForScanAndCheckBall(SEARCH_PRE_ALIGN_SCAN_MS)) {
      writeDebugStreamLine("Ball detected during pre-alignment scan rotation.");
      return SEARCH_RESULT_BALL_FOUND;
    }

    if (rotateCCWToWestAndCheckBall(SEARCH_ALIGN_TIMEOUT_MS)) {
      writeDebugStreamLine("Ball detected while aligning to WEST.");
      return SEARCH_RESULT_BALL_FOUND;
    }

    if (searchLowerSamples > 0) {
      writeDebugStreamLine(
        "SEARCH lower-tracking: triggered=%d peak=%d avg=%d",
        searchLowerTriggered,
        searchLowerPeak,
        (searchLowerSum / searchLowerSamples)
      );
    }
  }

  writeDebugStreamLine("SEARCH finished all %d cycles with no ball.", SEARCH_MAX_CYCLES);
  return SEARCH_RESULT_NO_BALL;
}

// -------------------------
// Collecting phase
// -------------------------
int isBallCollectedAtCenter() {
  return SensorValue[centerLight] > CENTER_BALL_COLLECT_MIN;
}

int runCollectingPhase() {
  int startTime = nSysTime;
  writeDebugStreamLine("COLLECTING started.");

  if (isBallCollectedAtCenter()) {
    stopDrive();
    writeDebugStreamLine("COLLECTING immediate success (ball already at center).");
    return COLLECT_RESULT_SUCCESS;
  }

  // Pre-align left-offset front-below sensor before forward retrieval.
  turnLeftInPlace(COLLECT_PRE_TURN_POWER);
  waitWithBoundaryCheck(COLLECT_PRE_TURN_MS);
  stopDrive();

  while ((nSysTime - startTime) < COLLECT_TIMEOUT_MS) {
    if (isBallCollectedAtCenter()) {
      stopDrive();
      writeDebugStreamLine("COLLECTING success before timeout.");
      return COLLECT_RESULT_SUCCESS;
    }

    setDrive(DRIVE_COLLECT_POWER, DRIVE_COLLECT_POWER);
    waitWithBoundaryCheck(20);
  }

  stopDrive();
  writeDebugStreamLine("COLLECTING forward timeout (1s). Extra collector spin starts.");

  startTime = nSysTime;
  motor[collectorMotor] = COLLECTOR_POWER;
  while ((nSysTime - startTime) < COLLECT_EXTRA_SPIN_TIMEOUT_MS) {
    if (isBallCollectedAtCenter()) {
      stopDrive();
      writeDebugStreamLine("COLLECTING success during extra collector spin.");
      return COLLECT_RESULT_SUCCESS;
    }
    waitWithBoundaryCheck(20);
  }

  writeDebugStreamLine("COLLECTING timeout after extra 5s collector spin.");
  return COLLECT_RESULT_TIMEOUT;
}

// -------------------------
// Depositing phase
// -------------------------
int isFacingEast() {
  return isEastAlignedExact();
}

void alignToEastCCW(int timeoutMs) {
  (void)timeoutMs;
  alignToEastForBoundaryRecovery();
}

void reverseStraightForMs(int durationMs) {
  int startTime = nSysTime;

  while ((nSysTime - startTime) < durationMs) {
    setDrive(-DRIVE_REVERSE_LEFT_POWER, -DRIVE_REVERSE_RIGHT_POWER);
    waitWithBoundaryCheck(20);
  }

  stopDrive();
}

int clampInt(int value, int minValue, int maxValue) {
  if (value < minValue) {
    return minValue;
  }
  if (value > maxValue) {
    return maxValue;
  }
  return value;
}

int gatePdPowerForTarget(int targetCount, int currentCount, int *prevAbsError) {
  int error = targetCount - currentCount;
  int absError = abs(error);
  int derivative = absError - *prevAbsError;
  float power = GATE_MIN_POWER + (GATE_PD_KP * absError) + (GATE_PD_KD * derivative);
  int mappedPower = clampInt((int)power, GATE_MIN_POWER, GATE_MAX_POWER);

  *prevAbsError = absError;
  return mappedPower;
}

void openGateByEncoder() {
  int openPrevAbsError = GATE_ENCODER_TARGET;
  int closePrevAbsError = GATE_ENCODER_POST_TARGET;
  int gatePower = 0;

  writeDebugStreamLine("Gate opening -> encoder target: %d counts.", GATE_ENCODER_TARGET);

  while (SensorValue[gateEncoder] < GATE_ENCODER_TARGET) {
    gatePower = gatePdPowerForTarget(GATE_ENCODER_TARGET, SensorValue[gateEncoder], &openPrevAbsError);
    motor[gateMotor] = -gatePower;
    waitWithBoundaryCheck(20);
  }

  motor[gateMotor] = 0;
  writeDebugStreamLine("Gate open hold for %d ms to allow ball drop.", GATE_OPEN_HOLD_MS);
  waitWithBoundaryCheck(GATE_OPEN_HOLD_MS);

  while (SensorValue[gateEncoder] > GATE_ENCODER_POST_TARGET) {
    gatePower = gatePdPowerForTarget(GATE_ENCODER_POST_TARGET, SensorValue[gateEncoder], &closePrevAbsError);
    motor[gateMotor] = gatePower;
    waitWithBoundaryCheck(20);
  }

  motor[gateMotor] = 0;
  waitWithBoundaryCheck(500);

  motor[gateMotor] = 0;
  writeDebugStreamLine("Gate closed. Final encoder count: %d.", SensorValue[gateEncoder]);
}

int reverseStraightAndCheckBack(int durationMs) {
  int startTime = nSysTime;

  // Deposit must always align EAST first before reversing.
  while (!isFacingEast()) {
    writeDebugStreamLine("DEPOSIT reverse pre-check: not EAST, aligning now.");
    alignToEastCCW(DEPOSIT_ALIGN_TIMEOUT_MS);
    waitWithBoundaryCheck(20);
  }

  while ((nSysTime - startTime) < durationMs) {
    if (SensorValue[backLight] >= BACK_SENSOR_DONE_MIN) {
      stopDrive();
      writeDebugStreamLine(
        "backLight=%d >= %d -> stopping reverse and opening gate.",
        SensorValue[backLight],
        BACK_SENSOR_DONE_MIN
      );
      openGateByEncoder();
      return 1;
    }

    setDrive(-DRIVE_REVERSE_LEFT_POWER, -DRIVE_REVERSE_RIGHT_POWER);
    waitWithBoundaryCheck(20);
  }

  stopDrive();
  return 0;
}

int isDepositCompleteNow() {
  int backValue = SensorValue[backLight];
  int facingEast = isFacingEast();
  return (backValue > BACK_SENSOR_DONE_MIN && facingEast);
}

int runDepositingPhase() {
  int phaseStart = nSysTime;
  int backValue = 0;
  int facingEast = 0;
  int depositCycle = 1;

  if (depositSequenceHasRun) {
    stopDrive();
    writeDebugStreamLine("DEPOSIT sequence already executed once. Skipping re-run.");
    return DEPOSIT_RESULT_TIMEOUT;
  }

  depositSequenceHasRun = 1;
  writeDebugStreamLine("DEPOSITING started.");
  alignToEastCCW(DEPOSIT_ALIGN_TIMEOUT_MS);

  if (reverseStraightAndCheckBack(DEPOSIT_INITIAL_REVERSE_MS)) {
    writeDebugStreamLine("DEPOSIT complete: backLight triggered gate during initial reverse.");
    return DEPOSIT_RESULT_STABLE;
  }

  while ((nSysTime - phaseStart) < DEPOSIT_TIMEOUT_MS) {
    backValue = SensorValue[backLight];
    facingEast = isFacingEast();
    writeDebugStreamLine(
      "DEPOSIT cycle %d check: back=%d facingEast=%d",
      depositCycle,
      backValue,
      facingEast
    );

    if (isDepositCompleteNow()) {
      writeDebugStreamLine("DEPOSIT complete: back>2500 and EAST aligned.");
      openGateByEncoder();
      return DEPOSIT_RESULT_STABLE;
    }

    if (!facingEast) {
      writeDebugStreamLine("DEPOSIT cycle %d: heading drifted, re-aligning to EAST.", depositCycle);
      alignToEastCCW(DEPOSIT_ALIGN_TIMEOUT_MS);
    }

    if (reverseStraightAndCheckBack(DEPOSIT_STEP_REVERSE_MS)) {
      writeDebugStreamLine("DEPOSIT complete: backLight triggered gate during step reverse.");
      return DEPOSIT_RESULT_STABLE;
    }
    depositCycle++;
  }

  stopDrive();
  writeDebugStreamLine("DEPOSIT timeout (10s).");
  return DEPOSIT_RESULT_TIMEOUT;
}

// -------------------------
// Transitions and main flow
// -------------------------
int runPhaseTransitionDelay() {
  int startTime = nSysTime;

  stopDrive();
  writeDebugStreamLine("Transition delay for %d ms.", PHASE_TRANSITION_DELAY_MS);

  while ((nSysTime - startTime) < PHASE_TRANSITION_DELAY_MS) {
    if (isBallCollectedAtCenter()) {
      stopDrive();
      writeDebugStreamLine("Transition interrupted: center sensor already has ball -> deposit now.");
      return 1;
    }
    waitWithBoundaryCheck(20);
  }

  return 0;
}

task main() {
  int searchResult = SEARCH_RESULT_NO_BALL;
  int collectResult = COLLECT_RESULT_TIMEOUT;
  int depositResult = DEPOSIT_RESULT_TIMEOUT;
  int delayInterruptedByCenter = 0;
  int depositHasRun = 0;

  clearDebugStream();
  writeDebugStreamLine("Competition flow started: SEARCH -> COLLECT -> DEPOSIT.");
  writeDebugStreamLine("Boundary mapping: floorValue=%d boundaryValue=%d", floorValue, boundaryValue);

  stopDrive();
  motor[collectorMotor] = SEARCH_COLLECTOR_POWER;

  if (isBallCollectedAtCenter()) {
    writeDebugStreamLine("Center sensor already has ball at start. Entering DEPOSIT immediately.");
    stopDrive();
    motor[collectorMotor] = 0;
    depositResult = runDepositingPhase();
    writeDebugStreamLine("DEPOSITING result = %d (1=stable, 0=timeout)", depositResult);
    depositHasRun = 1;
  }

  if (!depositHasRun) {
    searchResult = runSearchingPhase();
  }

  if (!depositHasRun && (searchCenterDetected || isBallCollectedAtCenter())) {
    writeDebugStreamLine("Center sensor has ball after SEARCH. Stopping and entering DEPOSIT immediately.");
    stopDrive();
    motor[collectorMotor] = 0;
    depositResult = runDepositingPhase();
    writeDebugStreamLine("DEPOSITING result = %d (1=stable, 0=timeout)", depositResult);
    depositHasRun = 1;
  }

  if (!depositHasRun && searchResult == SEARCH_RESULT_BALL_FOUND) {
    delayInterruptedByCenter = runPhaseTransitionDelay();

    if (delayInterruptedByCenter || isBallCollectedAtCenter()) {
      writeDebugStreamLine("Center sensor detected before COLLECT. Entering DEPOSIT immediately.");
      stopDrive();
      motor[collectorMotor] = 0;
      depositResult = runDepositingPhase();
      writeDebugStreamLine("DEPOSITING result = %d (1=stable, 0=timeout)", depositResult);
      depositHasRun = 1;
    } else {
      motor[collectorMotor] = COLLECTOR_POWER;
      collectResult = runCollectingPhase();
      writeDebugStreamLine("COLLECTING result = %d (1=success, 0=timeout)", collectResult);

      if (isBallCollectedAtCenter()) {
        writeDebugStreamLine("Center sensor has ball after COLLECT. Stopping and entering DEPOSIT immediately.");
        stopDrive();
        motor[collectorMotor] = 0;
        depositResult = runDepositingPhase();
        writeDebugStreamLine("DEPOSITING result = %d (1=stable, 0=timeout)", depositResult);
        depositHasRun = 1;
      } else {
        writeDebugStreamLine("Collecting did not succeed; depositing phase skipped.");
      }
    }
  }

  if (!depositHasRun && isBallCollectedAtCenter()) {
    writeDebugStreamLine("Center sensor has ball. Entering DEPOSIT immediately.");
    stopDrive();
    motor[collectorMotor] = 0;
    depositResult = runDepositingPhase();
    writeDebugStreamLine("DEPOSITING result = %d (1=stable, 0=timeout)", depositResult);
    depositHasRun = 1;
  }

  if (!depositHasRun && searchResult != SEARCH_RESULT_BALL_FOUND) {
    writeDebugStreamLine("No ball found in searching phase; collecting/depositing skipped.");
  }

  stopDrive();
  motor[collectorMotor] = 0;
  motor[gateMotor] = 0;
  writeDebugStreamLine("Competition pipeline complete (one-shot run finished).");
}
