#pragma config(Sensor, in5,    centerLight,    sensorAnalog)
#pragma config(Sensor, in6,    backLight,      sensorAnalog)
#pragma config(Sensor, in7,    frontUpperLight, sensorAnalog)
#pragma config(Sensor, in8,    frontBelowLight, sensorAnalog)
#pragma config(Sensor, dgtl1,  unusedD1,       sensorNone)
#pragma config(Sensor, dgtl2,  unusedD2,       sensorNone)
#pragma config(Sensor, dgtl3,  west,           sensorDigitalIn)
#pragma config(Sensor, dgtl4,  south,          sensorDigitalIn)
#pragma config(Sensor, dgtl5,  east,           sensorDigitalIn)
#pragma config(Sensor, dgtl6,  north,          sensorDigitalIn)
#pragma config(Sensor, dgtl7,  gateEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  backRightLine,  sensorDigitalIn)
#pragma config(Sensor, dgtl10, backLeftLine,   sensorDigitalIn)
#pragma config(Sensor, dgtl11, frontRightLine, sensorDigitalIn)
#pragma config(Sensor, dgtl12, frontLeftLine,  sensorDigitalIn)
#pragma config(Motor,  port6,           gateMotor,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           collectorMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightWheel,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftWheel,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// -------------------------
// Searching phase constants
// -------------------------
const int FRONT_LOWER_BALL_MIN = 1000;
const int FRONT_UPPER_BALL_MAX = 500;
const int SEARCH_FORWARD_MS = 1000;
const int SEARCH_FORWARD_FIRST_CYCLE_MS = 2000;
const int SEARCH_PRE_ALIGN_SCAN_MS = 2000;
const int SEARCH_ALIGN_TURN_POWER = 45;
const int SEARCH_MAX_CYCLES = 3;
const int SEARCH_ALIGN_TIMEOUT_MS = 5000;
const int SEARCH_POST_ALIGN_CCW_MS = 300;
const int BALL_CONFIRM_SAMPLES = 5;
const int BALL_DELTA_MIN = 500;
const int UPPER_SAFETY_BLOCK_MIN = 1800;
const int SEARCH_SAFETY_REVERSE_MS = 700;
const int SEARCH_SAFETY_REVERSE_POWER = 100;
const int DRIVE_FORWARD_POWER = 90;
const int SEARCH_RIGHT_WHEEL_OFFSET = 5;
const int SEARCH_COLLECTOR_POWER = 127;

const int SEARCH_RESULT_NO_BALL = 0;
const int SEARCH_RESULT_BALL_FOUND = 1;
const int SEARCH_RESULT_CENTER_CAPTURED = 2;

// -------------------------
// Collecting phase constants
// -------------------------
const int CENTER_BALL_COLLECT_MIN = 1300;
const int COLLECT_TIMEOUT_MS = 2000;
const int COLLECT_EXTRA_SPIN_TIMEOUT_MS = 1500;
const int DRIVE_COLLECT_POWER = 90;
const int COLLECT_PRE_TURN_POWER = 45;
const int COLLECT_PRE_TURN_MS = 500;
const int COLLECT_FALSE_UPPER_THRESHOLD = 900;
const int COLLECT_FALSE_UPPER_STEP_MIN = 3;
const int COLLECT_FALSE_UPPER_RISE_SAMPLES = 5;
const int COLLECT_FALSE_REVERSE_MS = 1000;
const int COLLECTOR_POWER = 200;

const int COLLECT_RESULT_TIMEOUT = 0;
const int COLLECT_RESULT_SUCCESS = 1;
const int COLLECT_RESULT_FALSE_DETECT = 2;

// -------------------------
// Depositing phase constants
// -------------------------
const int BACK_SENSOR_DONE_MIN        = 2000;
const int BACK_BOUNDARY_IGNORE_MIN    = 1800;
const int DEPOSIT_ALIGN_TIMEOUT_MS    = 5000;
const int DEPOSIT_INITIAL_REVERSE_MS  = 3000;
const int DEPOSIT_STEP_REVERSE_MS     = 1000;
const int DEPOSIT_TIMEOUT_MS          = 10000;
const int DRIVE_REVERSE_LEFT_POWER    = 80;
const int DRIVE_REVERSE_RIGHT_POWER   = 70; // Reverse deposit: right is 10 higher (-70 vs -80)

const int GATE_ENCODER_TARGET = 80;
const int GATE_ENCODER_POST_TARGET = 20;
const int GATE_MIN_POWER = 35;
const int GATE_MAX_POWER = 80;
const int GATE_OPEN_HOLD_MS = 5000;
const float GATE_PD_KP = 0.56;
const float GATE_PD_KD = 0.35;

const int DEPOSIT_RESULT_TIMEOUT = 0;
const int DEPOSIT_RESULT_STABLE = 1;
const int CYCLE_FAILURE_NONE = 0;
const int CYCLE_FAILURE_SEARCH_OR_COLLECT = 1;
const int CYCLE_FAILURE_DEPOSIT = 2;

// -------------------------
// Transition constants
// -------------------------
const int PHASE_TRANSITION_DELAY_MS = 0;
const int MODE_RUN_ONCE = 0;
const int MODE_RUN_CONTINUOUS = 1;
int competitionRunMode = MODE_RUN_CONTINUOUS; // change to MODE_RUN_CONTINUOUS for endless retries

// -------------------------
// Boundary safety constants (always-on across all phases)
// -------------------------
const int floorValue = 1;
const int boundaryValue = 0;
const int BOUNDARY_RECOVERY_POWER = 53;
const int BOUNDARY_FRONT_RECOVERY_MS = 500;
const int BOUNDARY_BACK_RECOVERY_MS = 500;
const int BOUNDARY_ALIGN_TURN_POWER = 55;
const int BOUNDARY_ALIGN_STABLE_SAMPLES = 3;

const int BOUNDARY_TRIGGER_NONE = 0;
const int BOUNDARY_TRIGGER_FRONT = 1;
const int BOUNDARY_TRIGGER_BACK = 2;
const int BOUNDARY_TRIGGER_BOTH = 3;

// -------------------------
// Shared state
// -------------------------
int searchLowerTriggered = 0;
int searchLowerPeak = 0;
int searchLowerSum = 0;
int searchLowerSamples = 0;
int searchLastDetectionCycle = -1;
int depositSequenceHasRun = 0;
int searchCenterDetected = 0;
int boundaryRecoveryActive = 0;
int lastCycleFailureReason = CYCLE_FAILURE_NONE;

int isBallCollectedAtCenter();
int checkAndHandleBoundaryRecovery();
void waitWithBoundaryCheck(int durationMs);
int isDepositCompleteNow();

void setDrive(int leftPower, int rightPower) {
  motor[leftWheel] = leftPower;
  motor[rightWheel] = rightPower;
}

void stopDrive() {
  setDrive(0, 0);
}

void turnLeftInPlace(int power) {
  setDrive(-power, power);
}

void setDepositReverseDrive() {
  setDrive(-DRIVE_REVERSE_LEFT_POWER, -DRIVE_REVERSE_RIGHT_POWER);
}

void setSearchForwardDrive() {
  setDrive(DRIVE_FORWARD_POWER, DRIVE_FORWARD_POWER - SEARCH_RIGHT_WHEEL_OFFSET);
}

void setSearchSafetyReverseDrive() {
  setDrive(-SEARCH_SAFETY_REVERSE_POWER, -(SEARCH_SAFETY_REVERSE_POWER - SEARCH_RIGHT_WHEEL_OFFSET));
}

int isBoundaryLine(int sensorValue) {
  return (sensorValue == boundaryValue);
}

int frontBoundaryDetected() {
  return (isBoundaryLine(SensorValue[frontLeftLine]) ||
          isBoundaryLine(SensorValue[frontRightLine]));
}

int backBoundaryDetected() {
  return (isBoundaryLine(SensorValue[backLeftLine]) ||
          isBoundaryLine(SensorValue[backRightLine]));
}

int detectBoundaryTrigger() {
  int frontTriggered = frontBoundaryDetected();
  int backTriggered = backBoundaryDetected();

  if (frontTriggered && backTriggered) return BOUNDARY_TRIGGER_BOTH;
  if (frontTriggered) return BOUNDARY_TRIGGER_FRONT;
  if (backTriggered) return BOUNDARY_TRIGGER_BACK;
  return BOUNDARY_TRIGGER_NONE;
}

void turnTowardHeadingCCWOnly(int turnPower) {
  // Alignment policy: always rotate counter-clockwise for stable, repeatable turns.
  if (turnPower < 0) turnPower = -turnPower;
  turnLeftInPlace(turnPower);
}

int isEastAlignedExact() {
  return (SensorValue[east] == 0 &&
          SensorValue[north] == 1 &&
          SensorValue[south] == 1 &&
          SensorValue[west] == 1);
}

void alignToEastForBoundaryRecovery() {
  int stableCount = 0;

  while (stableCount < BOUNDARY_ALIGN_STABLE_SAMPLES) {
    if (isEastAlignedExact()) {
      stableCount++;
      stopDrive();
      wait1Msec(20);
      continue;
    }

    stableCount = 0;
    turnTowardHeadingCCWOnly(BOUNDARY_ALIGN_TURN_POWER); // Target = EAST via CCW-only turning
    wait1Msec(25);
  }

  stopDrive();
  wait1Msec(80);
}

void recoverFromBoundary(int triggerSource) {
  boundaryRecoveryActive = 1;

  // Pure straight recovery only, then align to EAST.
  stopDrive();
  wait1Msec(40);

  if (triggerSource == BOUNDARY_TRIGGER_BACK) {
    setDrive(BOUNDARY_RECOVERY_POWER, BOUNDARY_RECOVERY_POWER);
    wait1Msec(BOUNDARY_BACK_RECOVERY_MS);
  } else {
    setDrive(-BOUNDARY_RECOVERY_POWER, -BOUNDARY_RECOVERY_POWER);
    wait1Msec(BOUNDARY_FRONT_RECOVERY_MS);
  }

  stopDrive();
  wait1Msec(80);
  alignToEastForBoundaryRecovery();
  boundaryRecoveryActive = 0;
}

int checkAndHandleBoundaryRecovery() {
  int trigger = BOUNDARY_TRIGGER_NONE;

  if (boundaryRecoveryActive) {
    return 0;
  }

  trigger = detectBoundaryTrigger();
  if (trigger == BOUNDARY_TRIGGER_NONE) {
    return 0;
  }

  recoverFromBoundary(trigger);
  return 1;
}

int checkAndHandleBoundaryRecoveryForDepositReverse() {
  int trigger = BOUNDARY_TRIGGER_NONE;

  if (boundaryRecoveryActive) {
    return 0;
  }

  trigger = detectBoundaryTrigger();
  if (trigger == BOUNDARY_TRIGGER_NONE) {
    return 0;
  }

  if (trigger == BOUNDARY_TRIGGER_BACK &&
      SensorValue[backLight] > BACK_BOUNDARY_IGNORE_MIN) {
    return 0;
  }

  recoverFromBoundary(trigger);
  return 1;
}

void waitWithBoundaryCheck(int durationMs) {
  int remaining = durationMs;

  while (remaining > 0) {
    checkAndHandleBoundaryRecovery();
    {
      int waitStep = (remaining > 10) ? 10 : remaining;
      wait1Msec(waitStep);
      remaining -= waitStep;
    }
  }
}

// -------------------------
// Searching phase
// -------------------------
int isBallCandidate() {
  int lower = SensorValue[frontBelowLight];
  int upper = SensorValue[frontUpperLight];

  return (lower > FRONT_LOWER_BALL_MIN &&
          upper < FRONT_UPPER_BALL_MAX &&
          (lower - upper) >= BALL_DELTA_MIN);
}

int isFrontLowerTriggered() {
  return SensorValue[frontBelowLight] > FRONT_LOWER_BALL_MIN;
}

int isFacingEastSearch() {
  return (SensorValue[west] == 1 &&
          SensorValue[south] == 1 &&
          SensorValue[east] == 0 &&
          SensorValue[north] == 1);
}

void resetSearchLowerTracking() {
  searchLowerTriggered = 0;
  searchLowerPeak = 0;
  searchLowerSum = 0;
  searchLowerSamples = 0;
}

void updateSearchLowerTracking() {
  int lower = SensorValue[frontBelowLight];
  if (lower > searchLowerPeak) searchLowerPeak = lower;
  searchLowerSum += lower;
  searchLowerSamples++;
  if (isFrontLowerTriggered()) searchLowerTriggered = 1;
}

int handleUpperSafetyReverse() {
  if (SensorValue[frontUpperLight] <= UPPER_SAFETY_BLOCK_MIN) {
    return 0;
  }

  setSearchSafetyReverseDrive();
  waitWithBoundaryCheck(SEARCH_SAFETY_REVERSE_MS);
  stopDrive();
  return 1;
}

int runForwardAndCheckBall(int durationMs) {
  int startTime = nSysTime;
  int ballConfirmCount = 0;

  while ((nSysTime - startTime) < durationMs) {
    if (isBallCollectedAtCenter()) {
      searchCenterDetected = 1;
      stopDrive();
      return SEARCH_RESULT_CENTER_CAPTURED;
    }

    updateSearchLowerTracking();

    if (handleUpperSafetyReverse()) {
      ballConfirmCount = 0;
      continue;
    }

    if (isBallCandidate()) {
      ballConfirmCount++;
      if (ballConfirmCount >= BALL_CONFIRM_SAMPLES) {
        stopDrive();
        return SEARCH_RESULT_BALL_FOUND;
      }
    } else {
      ballConfirmCount = 0;
    }

    setSearchForwardDrive();
    waitWithBoundaryCheck(20);
  }

  stopDrive();
  return SEARCH_RESULT_NO_BALL;
}

int rotateCCWForScanAndCheckBall(int durationMs) {
  int startTime = nSysTime;
  int ballConfirmCount = 0;

  while ((nSysTime - startTime) < durationMs) {
    if (isBallCollectedAtCenter()) {
      searchCenterDetected = 1;
      stopDrive();
      return SEARCH_RESULT_CENTER_CAPTURED;
    }

    updateSearchLowerTracking();

    if (handleUpperSafetyReverse()) {
      ballConfirmCount = 0;
      continue;
    }

    if (isBallCandidate()) {
      ballConfirmCount++;
      if (ballConfirmCount >= BALL_CONFIRM_SAMPLES) {
        stopDrive();
        return SEARCH_RESULT_BALL_FOUND;
      }
    } else {
      ballConfirmCount = 0;
    }

    turnLeftInPlace(SEARCH_ALIGN_TURN_POWER);
    waitWithBoundaryCheck(20);
  }

  stopDrive();
  return SEARCH_RESULT_NO_BALL;
}

int rotateCCWToEastAndCheckBall(int timeoutMs) {
  int startTime = nSysTime;
  int ballConfirmCount = 0;

  while ((nSysTime - startTime) < timeoutMs) {
    if (isBallCollectedAtCenter()) {
      searchCenterDetected = 1;
      stopDrive();
      return SEARCH_RESULT_CENTER_CAPTURED;
    }

    updateSearchLowerTracking();

    if (handleUpperSafetyReverse()) {
      ballConfirmCount = 0;
      continue;
    }

    if (isBallCandidate()) {
      ballConfirmCount++;
      if (ballConfirmCount >= BALL_CONFIRM_SAMPLES) {
        stopDrive();
        return SEARCH_RESULT_BALL_FOUND;
      }
    } else {
      ballConfirmCount = 0;
    }

    if (isFacingEastSearch()) {
      // Requested search behavior: after each EAST alignment, add a small CCW in-place nudge.
      turnTowardHeadingCCWOnly(SEARCH_ALIGN_TURN_POWER);
      waitWithBoundaryCheck(SEARCH_POST_ALIGN_CCW_MS);
      stopDrive();
      return SEARCH_RESULT_NO_BALL;
    }

    turnTowardHeadingCCWOnly(SEARCH_ALIGN_TURN_POWER); // Target = EAST via CCW-only turning
    waitWithBoundaryCheck(10);
  }

  stopDrive();
  return SEARCH_RESULT_NO_BALL;
}

int runSearchingPhase(int startCycle) {
  int cycle = startCycle;
  int forwardDurationMs = SEARCH_FORWARD_MS;
  int searchStepResult = SEARCH_RESULT_NO_BALL;
  searchCenterDetected = 0;


  for (cycle = startCycle; cycle < SEARCH_MAX_CYCLES; cycle++) {
    if (isBallCollectedAtCenter()) {
      searchCenterDetected = 1;
      searchLastDetectionCycle = cycle;
      stopDrive();
      return SEARCH_RESULT_CENTER_CAPTURED;
    }

    resetSearchLowerTracking();

    if (cycle == 0) {
      forwardDurationMs = SEARCH_FORWARD_FIRST_CYCLE_MS;
    } else {
      forwardDurationMs = SEARCH_FORWARD_MS;
    }

    searchStepResult = runForwardAndCheckBall(forwardDurationMs);
    if (searchStepResult == SEARCH_RESULT_CENTER_CAPTURED) {
      searchLastDetectionCycle = cycle;
      return SEARCH_RESULT_CENTER_CAPTURED;
    }
    if (searchStepResult == SEARCH_RESULT_BALL_FOUND) {
      searchLastDetectionCycle = cycle;
      return SEARCH_RESULT_BALL_FOUND;
    }

    searchStepResult = rotateCCWForScanAndCheckBall(SEARCH_PRE_ALIGN_SCAN_MS);
    if (searchStepResult == SEARCH_RESULT_CENTER_CAPTURED) {
      searchLastDetectionCycle = cycle;
      return SEARCH_RESULT_CENTER_CAPTURED;
    }
    if (searchStepResult == SEARCH_RESULT_BALL_FOUND) {
      searchLastDetectionCycle = cycle;
      return SEARCH_RESULT_BALL_FOUND;
    }

    searchStepResult = rotateCCWToEastAndCheckBall(SEARCH_ALIGN_TIMEOUT_MS);
    if (searchStepResult == SEARCH_RESULT_CENTER_CAPTURED) {
      searchLastDetectionCycle = cycle;
      return SEARCH_RESULT_CENTER_CAPTURED;
    }
    if (searchStepResult == SEARCH_RESULT_BALL_FOUND) {
      searchLastDetectionCycle = cycle;
      return SEARCH_RESULT_BALL_FOUND;
    }

    if (searchLowerSamples > 0) {
    }
  }

  return SEARCH_RESULT_NO_BALL;
}

// -------------------------
// Collecting phase
// -------------------------
int isBallCollectedAtCenter() {
  return SensorValue[centerLight] > CENTER_BALL_COLLECT_MIN;
}

int runCollectingPhase() {
  int startTime = nSysTime;
  int prevUpper = SensorValue[frontUpperLight];
  int upperRiseCount = 0;

  if (isBallCollectedAtCenter()) {
    stopDrive();
    return COLLECT_RESULT_SUCCESS;
  }

  // Pre-align left-offset front-below sensor before forward retrieval.
  turnTowardHeadingCCWOnly(COLLECT_PRE_TURN_POWER);
  waitWithBoundaryCheck(COLLECT_PRE_TURN_MS);
  stopDrive();

  while ((nSysTime - startTime) < COLLECT_TIMEOUT_MS) {
    int upper = SensorValue[frontUpperLight];

    if (isBallCollectedAtCenter()) {
      stopDrive();
      return COLLECT_RESULT_SUCCESS;
    }

    if ((upper - prevUpper) >= COLLECT_FALSE_UPPER_STEP_MIN) {
      upperRiseCount++;
    } else if (upper < prevUpper) {
      upperRiseCount = 0;
    }

    if (upper >= COLLECT_FALSE_UPPER_THRESHOLD &&
        upperRiseCount >= COLLECT_FALSE_UPPER_RISE_SAMPLES) {
      stopDrive();
      return COLLECT_RESULT_FALSE_DETECT;
    }

    prevUpper = upper;

    setDrive(DRIVE_COLLECT_POWER, DRIVE_COLLECT_POWER);
    waitWithBoundaryCheck(20);
  }

  stopDrive();

  startTime = nSysTime;
  motor[collectorMotor] = COLLECTOR_POWER;
  while ((nSysTime - startTime) < COLLECT_EXTRA_SPIN_TIMEOUT_MS) {
    if (isBallCollectedAtCenter()) {
      stopDrive();
      return COLLECT_RESULT_SUCCESS;
    }
    waitWithBoundaryCheck(20);
  }

  return COLLECT_RESULT_TIMEOUT;
}

void recoverFromCollectFalseDetection() {

  setDrive(-DRIVE_COLLECT_POWER, -DRIVE_COLLECT_POWER);
  waitWithBoundaryCheck(COLLECT_FALSE_REVERSE_MS);
  stopDrive();
  alignToEastForBoundaryRecovery();
  waitWithBoundaryCheck(80);
}

// -------------------------
// Depositing phase
// -------------------------
int isFacingEast() {
  return isEastAlignedExact();
}

void alignToEastCCW(int timeoutMs) {
  (void)timeoutMs;
  alignToEastForBoundaryRecovery();
}

int clampInt(int value, int minValue, int maxValue) {
  if (value < minValue) {
    return minValue;
  }
  if (value > maxValue) {
    return maxValue;
  }
  return value;
}

int gatePdPowerForTarget(int targetCount, int currentCount, int *prevAbsError) {
  int error = targetCount - currentCount;
  int absError = abs(error);
  int derivative = absError - *prevAbsError;
  float power = GATE_MIN_POWER + (GATE_PD_KP * absError) + (GATE_PD_KD * derivative);
  int mappedPower = clampInt((int)power, GATE_MIN_POWER, GATE_MAX_POWER);

  *prevAbsError = absError;
  return mappedPower;
}

void openGateByEncoder() {
  int openPrevAbsError = GATE_ENCODER_TARGET;
  int closePrevAbsError = GATE_ENCODER_POST_TARGET;
  int gatePower = 0;

  // Gate operation should not be interrupted by boundary handling.
  stopDrive();
  wait1Msec(40);


  while (SensorValue[gateEncoder] < GATE_ENCODER_TARGET) {
    gatePower = gatePdPowerForTarget(GATE_ENCODER_TARGET, SensorValue[gateEncoder], &openPrevAbsError);
    motor[gateMotor] = -gatePower;
    wait1Msec(20);
  }

  motor[gateMotor] = 0;
  wait1Msec(GATE_OPEN_HOLD_MS);

  while (SensorValue[gateEncoder] > GATE_ENCODER_POST_TARGET) {
    gatePower = gatePdPowerForTarget(GATE_ENCODER_POST_TARGET, SensorValue[gateEncoder], &closePrevAbsError);
    motor[gateMotor] = gatePower;
    wait1Msec(20);
  }

  motor[gateMotor] = 0;
  wait1Msec(500);

  motor[gateMotor] = 0;
}

int reverseStraightAndCheckBack(int durationMs) {
  int startTime = 0;

  // Deposit must always align EAST first before reversing.
  while (!isFacingEast()) {
    alignToEastCCW(DEPOSIT_ALIGN_TIMEOUT_MS);
  }

  startTime = nSysTime;
  while ((nSysTime - startTime) < durationMs) {
    // Deposit uses a dedicated boundary policy:
    // ignore back-line triggers only when backLight is above BACK_BOUNDARY_IGNORE_MIN.
    if (checkAndHandleBoundaryRecoveryForDepositReverse()) {
      continue;
    }

    if (isDepositCompleteNow()) {
      stopDrive();
      return 1;
    }

    setDepositReverseDrive();
    wait1Msec(20);
  }

  stopDrive();

  if (!isFacingEast()) {
    alignToEastCCW(DEPOSIT_ALIGN_TIMEOUT_MS);
    stopDrive();
  }

  return isDepositCompleteNow();
}

int isDepositCompleteNow() {
  int backValue = SensorValue[backLight];
  int facingEast = isFacingEast();
  return (backValue > BACK_SENSOR_DONE_MIN && facingEast);
}

void forceGateOpenWithFinalReverse() {
  // Timeout fallback: perform one final deterministic reverse segment, then force gate open.
  alignToEastCCW(DEPOSIT_ALIGN_TIMEOUT_MS);
  reverseStraightAndCheckBack(DEPOSIT_STEP_REVERSE_MS);
  stopDrive();
  openGateByEncoder();
}

int runDepositingPhase() {
  int phaseStart = nSysTime;
  int reverseCompletedAtTarget = 0;
  // Gate opening is blocked until the first 3s reverse segment is fully complete.
  int initialReverseComplete = 0;

  if (depositSequenceHasRun) {
    stopDrive();
    return DEPOSIT_RESULT_TIMEOUT;
  }

  depositSequenceHasRun = 1;
  alignToEastCCW(DEPOSIT_ALIGN_TIMEOUT_MS);

  reverseCompletedAtTarget = reverseStraightAndCheckBack(DEPOSIT_INITIAL_REVERSE_MS);
  initialReverseComplete = 1;

  stopDrive();
  if (initialReverseComplete && reverseCompletedAtTarget) {
    openGateByEncoder();
    return DEPOSIT_RESULT_STABLE;
  }

  while ((nSysTime - phaseStart) < DEPOSIT_TIMEOUT_MS) {
    // After each completed segment, re-align then run the next full reverse segment.
    alignToEastCCW(DEPOSIT_ALIGN_TIMEOUT_MS);

    reverseCompletedAtTarget = reverseStraightAndCheckBack(DEPOSIT_STEP_REVERSE_MS);
    if (reverseCompletedAtTarget && initialReverseComplete) {
      stopDrive();
      openGateByEncoder();
      return DEPOSIT_RESULT_STABLE;
    }
  }

  // Timed out: run one final 1s reverse attempt, then force gate open.
  forceGateOpenWithFinalReverse();
  return DEPOSIT_RESULT_STABLE;
}

// -------------------------
// Transitions and main flow
// -------------------------
int runPhaseTransitionDelay() {
  int startTime = nSysTime;

  stopDrive();

  while ((nSysTime - startTime) < PHASE_TRANSITION_DELAY_MS) {
    if (isBallCollectedAtCenter()) {
      stopDrive();
      return 1;
    }
    waitWithBoundaryCheck(20);
  }

  return 0;
}

void recoverAfterPhaseFailure() {
  int depositResult = DEPOSIT_RESULT_TIMEOUT;

  motor[collectorMotor] = 0;
  stopDrive();
  depositSequenceHasRun = 0; // allow recovery deposit to run even if this cycle touched deposit state
  depositResult = runDepositingPhase();
  stopDrive();
  waitWithBoundaryCheck(120);
}

void recoverAfterDepositFailure() {
  motor[collectorMotor] = 0;
  stopDrive();
  forceGateOpenWithFinalReverse();
  stopDrive();
  waitWithBoundaryCheck(120);
}

void resetCycleState() {
  searchCenterDetected = 0;
  searchLastDetectionCycle = -1;
  resetSearchLowerTracking();
  depositSequenceHasRun = 0;
  lastCycleFailureReason = CYCLE_FAILURE_NONE;
}

int runCompetitionCycle() {
  int searchResult = SEARCH_RESULT_NO_BALL;
  int collectResult = COLLECT_RESULT_TIMEOUT;
  int depositResult = DEPOSIT_RESULT_TIMEOUT;
  int delayInterruptedByCenter = 0;
  int searchStartCycle = 0;

  resetCycleState();
  stopDrive();
  motor[collectorMotor] = SEARCH_COLLECTOR_POWER;


  if (isBallCollectedAtCenter()) {
    stopDrive();
    motor[collectorMotor] = 0;
    depositResult = runDepositingPhase();
    if (depositResult == DEPOSIT_RESULT_STABLE) {
      return 1;
    }
    lastCycleFailureReason = CYCLE_FAILURE_DEPOSIT;
    return 0;
  }

  while (searchStartCycle < SEARCH_MAX_CYCLES) {
    searchResult = runSearchingPhase(searchStartCycle);

    if (searchResult == SEARCH_RESULT_CENTER_CAPTURED || searchCenterDetected || isBallCollectedAtCenter()) {
      stopDrive();
      motor[collectorMotor] = 0;
      depositResult = runDepositingPhase();
      if (depositResult == DEPOSIT_RESULT_STABLE) {
        return 1;
      }
      lastCycleFailureReason = CYCLE_FAILURE_DEPOSIT;
      return 0;
    }

    if (searchResult != SEARCH_RESULT_BALL_FOUND) {
      lastCycleFailureReason = CYCLE_FAILURE_SEARCH_OR_COLLECT;
      return 0;
    }

    delayInterruptedByCenter = runPhaseTransitionDelay();

    if (delayInterruptedByCenter || isBallCollectedAtCenter()) {
      stopDrive();
      motor[collectorMotor] = 0;
      depositResult = runDepositingPhase();
      if (depositResult == DEPOSIT_RESULT_STABLE) {
        return 1;
      }
      lastCycleFailureReason = CYCLE_FAILURE_DEPOSIT;
      return 0;
    }

    motor[collectorMotor] = COLLECTOR_POWER;
    collectResult = runCollectingPhase();

    if (collectResult == COLLECT_RESULT_FALSE_DETECT) {
      recoverFromCollectFalseDetection();
      motor[collectorMotor] = SEARCH_COLLECTOR_POWER;
      searchStartCycle = 0;
      continue;
    }

    if (collectResult == COLLECT_RESULT_SUCCESS || isBallCollectedAtCenter()) {
      runPhaseTransitionDelay();
      stopDrive();
      motor[collectorMotor] = 0;
      depositResult = runDepositingPhase();
      if (depositResult == DEPOSIT_RESULT_STABLE) {
        return 1;
      }
      lastCycleFailureReason = CYCLE_FAILURE_DEPOSIT;
      return 0;
    }

    lastCycleFailureReason = CYCLE_FAILURE_SEARCH_OR_COLLECT;
    return 0;
  }

  // Defensive fallback: treat any natural loop exit as the same search-failed outcome.
  lastCycleFailureReason = CYCLE_FAILURE_SEARCH_OR_COLLECT;
  return 0;
}

task main() {
  int cycleSuccess = 0;

  while (true) {
    cycleSuccess = runCompetitionCycle();

    if (competitionRunMode == MODE_RUN_ONCE) {
      break;
    }

    if (!cycleSuccess) {
      if (lastCycleFailureReason == CYCLE_FAILURE_DEPOSIT) {
        recoverAfterDepositFailure();
      } else {
        recoverAfterPhaseFailure();
      }
    } else {
      stopDrive();
      waitWithBoundaryCheck(120);
    }
  }

  stopDrive();
  motor[collectorMotor] = 0;
  motor[gateMotor] = 0;
}
