#pragma config(Sensor, in1,    LineSensor,     sensorAnalog)
#pragma config(Motor,  port6,           gateMotor,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           collectorMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftWheel,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightWheel,    tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
    int THRESHOLD = 900;

    while(true)
    {
        //int v = SensorValue[LineSensor];
    		int v = 0;

        if(v > THRESHOLD)
        {
        		motor[leftWheel] = 40;
            motor[rightWheel] = 40;
            wait1Msec(500);

            motor[leftWheel] = 40;
            motor[rightWheel] = 40;
        }
        else
        {
            motor[leftWheel] = 0;
            motor[rightWheel] = 0;
        }
				motor[collectorMotor] = 130;
        wait1Msec(50);
    }
}
