#pragma config(Sensor, in1,    frontBelowLight, sensorAnalog)
#pragma config(Sensor, in2,    frontUpperLight, sensorAnalog)
#pragma config(Sensor, in3,    centerLight,     sensorAnalog)
#pragma config(Sensor, in4,    backLight,       sensorAnalog)
#pragma config(Sensor, dgtl1,  frontLeftLine,   sensorDigitalIn)
#pragma config(Sensor, dgtl2,  frontRightLine,  sensorDigitalIn)
#pragma config(Sensor, dgtl3,  backLeftLine,    sensorDigitalIn)
#pragma config(Sensor, dgtl4,  backRightLine,   sensorDigitalIn)
#pragma config(Sensor, dgtl5,  unusedD5,        sensorNone)
#pragma config(Sensor, dgtl6,  unusedD6,        sensorNone)
#pragma config(Sensor, dgtl7,  unusedD7,        sensorNone)
#pragma config(Sensor, dgtl8,  unusedD8,        sensorNone)
#pragma config(Sensor, dgtl9,  compassLSB,      sensorDigitalIn)
#pragma config(Sensor, dgtl10, compassBit1,     sensorDigitalIn)
#pragma config(Sensor, dgtl11, compassBit2,     sensorDigitalIn)
#pragma config(Sensor, dgtl12, compassMSB,      sensorDigitalIn)
#pragma config(Motor,  port1,  rightWheel,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port2,  leftWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,  collectorMotor,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,  gateMotor,       tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



/*
  compass_test.c
  Reads 4-bit digital compass output and maps it to heading names.
*/

int readCompassCode() {
  return (SensorValue[compassMSB] << 3) +
         (SensorValue[compassBit2] << 2) +
         (SensorValue[compassBit1] << 1) +
         SensorValue[compassLSB];
}

string headingNameFromCode(int code) {
  switch (code) {
    case 14: return "N";
    case 12: return "NE";
    case 13: return "E";
    case 9:  return "SE";
    case 11: return "S";
    case 3:  return "SW";
    case 7:  return "W";
    case 6:  return "NW";
    default: return "UNKNOWN";
  }
}

task main() {
  clearDebugStream();
  writeDebugStreamLine("Compass test started.");

  while (true) {
    int b0 = SensorValue[compassLSB];
    int b1 = SensorValue[compassBit1];
    int b2 = SensorValue[compassBit2];
    int b3 = SensorValue[compassMSB];
    int code = readCompassCode();
    string heading = headingNameFromCode(code);

    writeDebugStreamLine(
      "bits(MSB..LSB)=%d%d%d%d code=%d heading=%s",
      b3, b2, b1, b0, code, heading
    );

    wait1Msec(150);
  }
}
