#pragma config(Sensor, in5,    centerLight,    sensorAnalog)
#pragma config(Sensor, in6,    backLight,      sensorAnalog)
#pragma config(Sensor, in7,    frontUpperLight, sensorAnalog)
#pragma config(Sensor, in8,    frontBelowLight, sensorAnalog)
#pragma config(Sensor, dgtl1,  unusedD1,       sensorNone)
#pragma config(Sensor, dgtl2,  unusedD2,       sensorNone)
#pragma config(Sensor, dgtl3,  west,           sensorDigitalIn)
#pragma config(Sensor, dgtl4,  south,          sensorDigitalIn)
#pragma config(Sensor, dgtl5,  east,           sensorDigitalIn)
#pragma config(Sensor, dgtl6,  north,           sensorDigitalIn)
#pragma config(Sensor, dgtl9,  backRightLine,         sensorDigitalIn)
#pragma config(Sensor, dgtl10, backLeftLine,          sensorDigitalIn)
#pragma config(Sensor, dgtl11, frontRightLine,            sensorDigitalIn)
#pragma config(Sensor, dgtl12, frontLeftLine,            sensorDigitalIn)
#pragma config(Motor,  port6,           gateMotor,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           collectorMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightWheel,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftWheel,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//




/*
  compass_test.c
  Reads cardinal compass outputs:
  - west/south/east/north
  - active-low (0 means that direction is active)
*/

int readCompassDirectionIndex() {
  if (SensorValue[north] == 0) return 0; // N
  if (SensorValue[east] == 0) return 1; // E
  if (SensorValue[south] == 0) return 2; // S
  if (SensorValue[west] == 0) return 3; // W
  return -1;
}

task main() {
  clearDebugStream();
  writeDebugStreamLine("Compass test started.");

  while (true) {
    int w = SensorValue[west];
    int s = SensorValue[south];
    int e = SensorValue[east];
    int n = SensorValue[north];
    int headingIndex = readCompassDirectionIndex();
    string heading;

    switch (headingIndex) {
      case 0: heading = "N"; break;
      case 1: heading = "E"; break;
      case 2: heading = "S"; break;
      case 3: heading = "W"; break;
      default: heading = "UNKNOWN"; break;
    }

    writeDebugStreamLine(
      "W=%d S=%d E=%d N=%d (0=active) heading=%s",
      w, s, e, n, heading
    );

    wait1Msec(150);
  }
}
