#pragma config(Sensor, in5,    centerLight,    sensorAnalog)
#pragma config(Sensor, in6,    backLight,      sensorAnalog)
#pragma config(Sensor, in7,    frontUpperLight, sensorAnalog)
#pragma config(Sensor, in8,    frontBelowLight, sensorAnalog)
#pragma config(Sensor, dgtl1,  unusedD1,       sensorNone)
#pragma config(Sensor, dgtl2,  unusedD2,       sensorNone)
#pragma config(Sensor, dgtl3,  west,           sensorDigitalIn)
#pragma config(Sensor, dgtl4,  south,          sensorDigitalIn)
#pragma config(Sensor, dgtl5,  east,           sensorDigitalIn)
#pragma config(Sensor, dgtl6,  noth,           sensorDigitalIn)
#pragma config(Sensor, dgtl7,  unusedD7,       sensorNone)
#pragma config(Sensor, dgtl8,  unusedD8,       sensorNone)
#pragma config(Sensor, dgtl9,  yellow,         sensorDigitalOut)
#pragma config(Sensor, dgtl10, green,          sensorDigitalOut)
#pragma config(Sensor, dgtl11, red,            sensorDigitalOut)
#pragma config(Motor,  port6,           gateMotor,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           collectorMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightWheel,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftWheel,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  east_alignment_accuracy_test.c

  Test flow (repeats):
  1) Rotate robot for a random duration and random direction.
  2) Align robot back to EAST using compass digital inputs.
  3) Log per-trial + running accuracy statistics.

  Compass is treated as active-low:
    0 = active direction, 1 = inactive
*/

const int RANDOM_SPIN_MIN_MS = 300;
const int RANDOM_SPIN_MAX_MS = 2200;
const int RANDOM_TURN_POWER = 50;
const int ALIGN_TURN_POWER = 50;
const int ALIGN_TIMEOUT_MS = 5000;
const int INTER_TRIAL_PAUSE_MS = 700;

const int REPEAT_FOREVER = 1; // 1 = continuous test
const int MAX_TRIALS = 20;    // used only when REPEAT_FOREVER = 0

int rngState = 1;

void setDrive(int leftPower, int rightPower) {
  motor[leftWheel] = leftPower;
  motor[rightWheel] = rightPower;
}

void stopAll() {
  motor[leftWheel] = 0;
  motor[rightWheel] = 0;
  motor[collectorMotor] = 0;
  motor[gateMotor] = 0;
}

void rotateCW(int power) {
  setDrive(power, -power);
}

void rotateCCW(int power) {
  setDrive(-power, power);
}

void setStatusLeds(int y, int g, int r) {
  SensorValue[yellow] = y;
  SensorValue[green] = g;
  SensorValue[red] = r;
}

int readCompassDirectionIndex() {
  if (SensorValue[noth] == 0) return 0;  // N
  if (SensorValue[east] == 0) return 1;  // E
  if (SensorValue[south] == 0) return 2; // S
  if (SensorValue[west] == 0) return 3;  // W
  return -1;                             // unknown / invalid
}

int isStrictEast() {
  return (SensorValue[east] == 0 &&
          SensorValue[noth] == 1 &&
          SensorValue[south] == 1 &&
          SensorValue[west] == 1);
}

int headingErrorStepsFromEast(int headingIndex) {
  if (headingIndex < 0) return 3;

  // Cardinal step error: 0=E, 1=90deg off, 2=180deg off.
  int cwSteps = (1 - headingIndex + 4) % 4;
  int ccwSteps = (headingIndex - 1 + 4) % 4;
  if (cwSteps < ccwSteps) return cwSteps;
  return ccwSteps;
}

void seedRng() {
  rngState = nSysTime + SensorValue[west] * 13 + SensorValue[south] * 17 +
             SensorValue[east] * 19 + SensorValue[noth] * 23 + 97;
  if (rngState <= 0) {
    rngState = 97;
  }
}

int randRange(int minValue, int maxValue) {
  int span = maxValue - minValue + 1;

  // Small LCG to avoid relying on stdlib random APIs.
  rngState = (rngState * 25173 + 13849) % 65536;
  if (rngState < 0) rngState = -rngState;

  return minValue + (rngState % span);
}

void randomSpin(int spinCw, int durationMs) {
  int startTime = nSysTime;
  while ((nSysTime - startTime) < durationMs) {
    if (spinCw) {
      rotateCW(RANDOM_TURN_POWER);
    } else {
      rotateCCW(RANDOM_TURN_POWER);
    }
    wait1Msec(20);
  }
  stopAll();
}

int alignToEast(int timeoutMs) {
  int startTime = nSysTime;

  while ((nSysTime - startTime) < timeoutMs) {
    if (isStrictEast()) {
      stopAll();
      return 1;
    }

    int currentHeading = readCompassDirectionIndex();
    if (currentHeading < 0) {
      rotateCW(ALIGN_TURN_POWER);
      wait1Msec(70);
      continue;
    }

    // Shortest turn on 4-direction ring N(0)-E(1)-S(2)-W(3).
    int cwStepsToEast = (1 - currentHeading + 4) % 4;
    if (cwStepsToEast <= 2) {
      rotateCW(ALIGN_TURN_POWER);
    } else {
      rotateCCW(ALIGN_TURN_POWER);
    }

    wait1Msec(70);
  }

  stopAll();
  return 0;
}

task main() {
  int trials = 0;
  int strictEastCount = 0;
  int alignSuccessCount = 0;
  int timeoutCount = 0;
  int unknownAfterCount = 0;
  int totalErrorSteps = 0;

  clearDebugStream();
  stopAll();
  setStatusLeds(0, 0, 0);
  seedRng();

  writeDebugStreamLine("East alignment accuracy test started.");
  writeDebugStreamLine("Random spin + align-to-east each trial.");

  while (true) {
    int spinMs = randRange(RANDOM_SPIN_MIN_MS, RANDOM_SPIN_MAX_MS);
    int spinCw = randRange(0, 1);

    int headingBefore;
    int aligned;
    int alignMs;
    int headingAfter;
    int strictEast;
    int errorSteps;
    int avgErrorX100;
    int strictPct;
    int alignPct;
    int alignStartMs;

    trials++;
    setStatusLeds(1, 0, 0);

    writeDebugStreamLine(
      "Trial %d: random spin %s for %d ms",
      trials, (spinCw ? "CW" : "CCW"), spinMs
    );

    randomSpin(spinCw, spinMs);
    wait1Msec(120);

    headingBefore = readCompassDirectionIndex();
    alignStartMs = nSysTime;
    aligned = alignToEast(ALIGN_TIMEOUT_MS);
    alignMs = nSysTime - alignStartMs;
    headingAfter = readCompassDirectionIndex();
    strictEast = isStrictEast();
    errorSteps = headingErrorStepsFromEast(headingAfter);

    if (aligned) {
      alignSuccessCount++;
    } else {
      timeoutCount++;
    }
    if (strictEast) {
      strictEastCount++;
      setStatusLeds(0, 1, 0);
    } else {
      setStatusLeds(0, 0, 1);
    }
    if (headingAfter < 0) {
      unknownAfterCount++;
    }

    totalErrorSteps += errorSteps;
    avgErrorX100 = (totalErrorSteps * 100) / trials;
    strictPct = (strictEastCount * 100) / trials;
    alignPct = (alignSuccessCount * 100) / trials;

    writeDebugStreamLine(
      "Result %d: aligned=%d strictEast=%d beforeIdx=%d afterIdx=%d errorSteps=%d alignMs=%d rawW/S/E/N=%d/%d/%d/%d",
      trials, aligned, strictEast, headingBefore, headingAfter, errorSteps, alignMs,
      SensorValue[west], SensorValue[south], SensorValue[east], SensorValue[noth]
    );
    writeDebugStreamLine(
      "Stats: strict=%d/%d (%d%%) alignSuccess=%d/%d (%d%%) timeout=%d unknownAfter=%d avgErrorX100=%d",
      strictEastCount, trials, strictPct,
      alignSuccessCount, trials, alignPct,
      timeoutCount, unknownAfterCount, avgErrorX100
    );

    wait1Msec(INTER_TRIAL_PAUSE_MS);

    if (!REPEAT_FOREVER && trials >= MAX_TRIALS) {
      break;
    }
  }

  stopAll();
  setStatusLeds(0, 1, 0);
  writeDebugStreamLine("East alignment accuracy test completed.");
}
