#pragma config(Sensor, in5,    centerLight,    sensorAnalog)
#pragma config(Sensor, in6,    backLight,      sensorAnalog)
#pragma config(Sensor, in7,    frontUpperLight, sensorAnalog)
#pragma config(Sensor, in8,    frontBelowLight, sensorAnalog)
#pragma config(Sensor, dgtl1,  unusedD1,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  west,           sensorDigitalIn)
#pragma config(Sensor, dgtl4,  south,          sensorDigitalIn)
#pragma config(Sensor, dgtl5,  east,           sensorDigitalIn)
#pragma config(Sensor, dgtl6,  noth,           sensorDigitalIn)
#pragma config(Sensor, dgtl7,  gateEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  yellow,         sensorDigitalOut)
#pragma config(Sensor, dgtl10, green,          sensorDigitalOut)
#pragma config(Sensor, dgtl11, red,            sensorDigitalOut)
#pragma config(Motor,  port6,           gateMotor,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           collectorMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightWheel,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftWheel,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Compatibility aliases for legacy encoder demo names.

/*----------------------------------------------------------------------------------------------------*\
|*                                      - Movement by Rotation -                                      *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program uses the Shaft Encoders to move forward for a certain distance.                      *|
|*  There is a two second pause at the beginning of the program.                                      *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
|*    2)  Changing the value of 'distance' will change how far your robot will travel.                *|
|*        !! 360 is equal to one full rotation of the axel !!                                         *|
|*    3)  Whichever encoder is being used for feedback should be cleared just before it starts        *|
|*        counting by using the "SensorValue(encoder) = 0;".  This helps ensure consistancy.          *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor   - Port 2    rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor   - Port 3    leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Digital - Port 1,2  rightEncoder        VEX Quadrature enc.   Right side encoder                *|
|*    Digital - Port 3,4  leftEncoder         VEX Quadrature enc.   Left side encoder                 *|
\*-----------------------------------------------------------------------------------------------4246-*/



//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
  wait1Msec(2000);                  // Wait 2000 milliseconds before continuing.

  int distance;                     // Create an integer variable 'distance' that will represent encoder counts.
  distance = 90;                   // 360 encoder counts is a full rotation of the axel.

  // SensorValue[gateEncoder]  = 0;    /* Clear the encoders for    */
  /* consistancy and accuracy. */

  while(SensorValue[gateEncoder] < distance) // While the left encoder is less than distance:
  {
    motor[gateMotor]  = -40;         /* forward at half speed. */
  }

  motor[gateMotor]  = 0;            /* distance has been reached.   */
  wait1Msec(500);
  while(SensorValue[gateEncoder] > 0) // While the left encoder is less than distance:
  {
    motor[gateMotor]  = 40;         /* forward at half speed. */
  }

  motor[gateMotor] = 0;
  wait1Msec(500);

}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
