#pragma config(Sensor, in5,    centerLight,    sensorAnalog)
#pragma config(Sensor, in6,    backLight,      sensorAnalog)
#pragma config(Sensor, in7,    frontUpperLight, sensorAnalog)
#pragma config(Sensor, in8,    frontBelowLight, sensorAnalog)
#pragma config(Sensor, dgtl1,  unusedD1,       sensorNone)
#pragma config(Sensor, dgtl2,  unusedD2,       sensorNone)
#pragma config(Sensor, dgtl3,  west,           sensorDigitalIn)
#pragma config(Sensor, dgtl4,  south,          sensorDigitalIn)
#pragma config(Sensor, dgtl5,  east,           sensorDigitalIn)
#pragma config(Sensor, dgtl6,  noth,           sensorDigitalIn)
#pragma config(Sensor, dgtl7,  unusedD7,       sensorNone)
#pragma config(Sensor, dgtl8,  unusedD8,       sensorNone)
#pragma config(Sensor, dgtl9,  yellow,         sensorDigitalOut)
#pragma config(Sensor, dgtl10, green,          sensorDigitalOut)
#pragma config(Sensor, dgtl11, red,            sensorDigitalOut)
#pragma config(Motor,  port6,           gateMotor,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           collectorMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightWheel,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftWheel,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  forward_motion_test.c
  Simple straight forward drive test for wheel motors.
*/

const int FORWARD_POWER = 60;
const int STOP_MS = 3000;

void setDrive(int leftPower, int rightPower) {
  motor[leftWheel] = leftPower;
  motor[rightWheel] = rightPower;
}

void stopAll() {
  motor[leftWheel] = 0;
  motor[rightWheel] = 0;
  motor[collectorMotor] = 0;
  motor[gateMotor] = 0;
}

task main() {
  clearDebugStream();
  writeDebugStreamLine("Forward motion test started.");

  setDrive(-FORWARD_POWER, -FORWARD_POWER);
  wait1Msec(STOP_MS);
  stopAll();
  //while (true) {
    //setDrive(-FORWARD_POWER, -FORWARD_POWER);
    //wait1Msec(STOP_MS);
    //stopAll();
  //}
}
