#pragma config(Sensor, in5,    centerLight,    sensorAnalog)
#pragma config(Sensor, in6,    backLight,      sensorAnalog)
#pragma config(Sensor, in7,    frontUpperLight, sensorAnalog)
#pragma config(Sensor, in8,    frontBelowLight, sensorAnalog)
#pragma config(Sensor, dgtl1,  unusedD1,       sensorNone)
#pragma config(Sensor, dgtl2,  unusedD2,       sensorNone)
#pragma config(Sensor, dgtl3,  west,           sensorDigitalIn)
#pragma config(Sensor, dgtl4,  south,          sensorDigitalIn)
#pragma config(Sensor, dgtl5,  east,           sensorDigitalIn)
#pragma config(Sensor, dgtl6,  north,           sensorDigitalIn)
#pragma config(Sensor, dgtl9,  backRightLine,         sensorDigitalIn)
#pragma config(Sensor, dgtl10, backLeftLine,          sensorDigitalIn)
#pragma config(Sensor, dgtl11, frontRightLine,            sensorDigitalIn)
#pragma config(Sensor, dgtl12, frontLeftLine,            sensorDigitalIn)
#pragma config(Motor,  port6,           gateMotor,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           collectorMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightWheel,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftWheel,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Compatibility aliases for legacy LED test names.
#define led1 yellow
#define led2 green
#define led3 red

task main()
{
    while(true)
    {
        // Step 1
        SensorValue[led1] = 1;
        SensorValue[led2] = 0;
        SensorValue[led3] = 0;
        wait1Msec(500);

        // Step 2
        SensorValue[led1] = 0;
        SensorValue[led2] = 1;
        SensorValue[led3] = 0;
        wait1Msec(500);

        // Step 3
        SensorValue[led1] = 0;
        SensorValue[led2] = 0;
        SensorValue[led3] = 1;
        wait1Msec(500);
    }
}
