#pragma config(Sensor, in8,    frontBelowLight, sensorAnalog)
#pragma config(Sensor, in7,    frontUpperLight, sensorAnalog)
#pragma config(Sensor, in5,    centerLight,     sensorAnalog)
#pragma config(Sensor, in6,    backLight,       sensorAnalog)
#pragma config(Sensor, dgtl12,  frontLeftLine,   sensorDigitalIn)
#pragma config(Sensor, dgtl11,  frontRightLine,  sensorDigitalIn)
#pragma config(Sensor, dgtl10,  backLeftLine,    sensorDigitalIn)
#pragma config(Sensor, dgtl9,  backRightLine,   sensorDigitalIn)
#pragma config(Sensor, dgtl1,  unusedD1,        sensorNone)
#pragma config(Sensor, dgtl2,  unusedD2,        sensorNone)
#pragma config(Sensor, dgtl7,  unusedD7,        sensorNone)
#pragma config(Sensor, dgtl8,  unusedD8,        sensorNone)
#pragma config(Sensor, dgtl3,  west,      sensorDigitalIn)
#pragma config(Sensor, dgtl4,  south,     sensorDigitalIn)
#pragma config(Sensor, dgtl5,  east,     sensorDigitalIn)
#pragma config(Sensor, dgtl6,  noth,      sensorDigitalIn)
#pragma config(Motor,  port6,           gateMotor,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           collectorMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightWheel,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftWheel,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



/*
  light_sensor_test.c
  Streams raw analog readings plus simple classification flags.
  Tune the threshold constants below on your arena before final run.
*/

const int FRONT_BELOW_BALL_MIN = 1400;
const int FRONT_BELOW_BALL_MAX = 3600;
const int FRONT_UPPER_OBSTACLE_MIN = 1200;
const int CENTER_BALL_COLLECT_MIN = 1200;
const int BACK_DEPOSIT_TRIGGER_MIN = 2400;

int isBallCandidate() {
  int lower = SensorValue[frontBelowLight];
  int upper = SensorValue[frontUpperLight];
  return (lower >= FRONT_BELOW_BALL_MIN &&
          lower <= FRONT_BELOW_BALL_MAX &&
          upper < FRONT_UPPER_OBSTACLE_MIN);
}

int isObstacleCandidate() {
  return SensorValue[frontUpperLight] >= FRONT_UPPER_OBSTACLE_MIN;
}

task main() {
  clearDebugStream();
  writeDebugStreamLine("Light sensor test started.");

  while (true) {
    int below = SensorValue[frontBelowLight];
    int upper = SensorValue[frontUpperLight];
    int center = SensorValue[centerLight];
    int back = SensorValue[backLight];

    writeDebugStreamLine(
      "below=%d upper=%d center=%d back=%d | ball=%d obstacle=%d centerBall=%d backNear=%d",
      below,
      upper,
      center,
      back,
      isBallCandidate(),
      isObstacleCandidate(),
      (center > CENTER_BALL_COLLECT_MIN),
      (back > BACK_DEPOSIT_TRIGGER_MIN)
    );

    wait1Msec(120);
  }
}
