#pragma config(Sensor, in1,    frontBelowLight, sensorAnalog)
#pragma config(Sensor, in2,    frontUpperLight, sensorAnalog)
#pragma config(Sensor, in3,    centerLight,     sensorAnalog)
#pragma config(Sensor, in4,    backLight,       sensorAnalog)
#pragma config(Sensor, dgtl1,  frontLeftLine,   sensorDigitalIn)
#pragma config(Sensor, dgtl2,  frontRightLine,  sensorDigitalIn)
#pragma config(Sensor, dgtl3,  backLeftLine,    sensorDigitalIn)
#pragma config(Sensor, dgtl4,  backRightLine,   sensorDigitalIn)
#pragma config(Sensor, dgtl5,  unusedD5,        sensorNone)
#pragma config(Sensor, dgtl6,  unusedD6,        sensorNone)
#pragma config(Sensor, dgtl7,  unusedD7,        sensorNone)
#pragma config(Sensor, dgtl8,  unusedD8,        sensorNone)
#pragma config(Sensor, dgtl9,  compassLSB,      sensorDigitalIn)
#pragma config(Sensor, dgtl10, compassBit1,     sensorDigitalIn)
#pragma config(Sensor, dgtl11, compassBit2,     sensorDigitalIn)
#pragma config(Sensor, dgtl12, compassMSB,      sensorDigitalIn)
#pragma config(Motor,  port1,  rightWheel,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port2,  leftWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,  collectorMotor,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,  gateMotor,       tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



/*
  light_sensor_test.c
  Streams raw analog readings plus simple classification flags.
  Tune the threshold constants below on your arena before final run.
*/

const int FRONT_BELOW_BALL_MIN = 1400;
const int FRONT_BELOW_BALL_MAX = 3600;
const int FRONT_UPPER_OBSTACLE_MIN = 1200;
const int CENTER_BALL_INSIDE_MIN = 1600;
const int BACK_COLLECTION_NEAR_MIN = 1700;

int isBallCandidate() {
  int lower = SensorValue[frontBelowLight];
  int upper = SensorValue[frontUpperLight];
  return (lower >= FRONT_BELOW_BALL_MIN &&
          lower <= FRONT_BELOW_BALL_MAX &&
          upper < FRONT_UPPER_OBSTACLE_MIN);
}

int isObstacleCandidate() {
  return SensorValue[frontUpperLight] >= FRONT_UPPER_OBSTACLE_MIN;
}

task main() {
  clearDebugStream();
  writeDebugStreamLine("Light sensor test started.");

  while (true) {
    int below = SensorValue[frontBelowLight];
    int upper = SensorValue[frontUpperLight];
    int center = SensorValue[centerLight];
    int back = SensorValue[backLight];

    writeDebugStreamLine(
      "below=%d upper=%d center=%d back=%d | ball=%d obstacle=%d centerBall=%d backNear=%d",
      below,
      upper,
      center,
      back,
      isBallCandidate(),
      isObstacleCandidate(),
      (center >= CENTER_BALL_INSIDE_MIN),
      (back >= BACK_COLLECTION_NEAR_MIN)
    );

    wait1Msec(120);
  }
}
