#pragma config(Sensor, in4,    frontBelowLight, sensorAnalog)
#pragma config(Sensor, in3,    frontUpperLight, sensorAnalog)
#pragma config(Sensor, in2,    centerLight,     sensorAnalog)
#pragma config(Sensor, in1,    backLight,       sensorAnalog)
#pragma config(Sensor, dgtl12,  frontLeftLine,   sensorDigitalIn)
#pragma config(Sensor, dgtl11,  frontRightLine,  sensorDigitalIn)
#pragma config(Sensor, dgtl10,  backLeftLine,    sensorDigitalIn)
#pragma config(Sensor, dgtl9,  backRightLine,   sensorDigitalIn)
#pragma config(Sensor, dgtl1,  unusedD1,        sensorNone)
#pragma config(Sensor, dgtl2,  unusedD2,        sensorNone)
#pragma config(Sensor, dgtl7,  unusedD7,        sensorNone)
#pragma config(Sensor, dgtl8,  unusedD8,        sensorNone)
#pragma config(Sensor, dgtl3,  west,      sensorDigitalIn)
#pragma config(Sensor, dgtl4,  south,     sensorDigitalIn)
#pragma config(Sensor, dgtl5,  east,     sensorDigitalIn)
#pragma config(Sensor, dgtl6,  noth,      sensorDigitalIn)
#pragma config(Motor,  port6,           gateMotor,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           collectorMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightWheel,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftWheel,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



/*
  line_sensor_test.c
  Shows all four line sensor states (0 means yellow boundary detected).
*/

task main() {
  clearDebugStream();
  writeDebugStreamLine("Line sensor test started.");

  while (true) {
    int fl = SensorValue[frontLeftLine];
    int fr = SensorValue[frontRightLine];
    int bl = SensorValue[backLeftLine];
    int br = SensorValue[backRightLine];

    writeDebugStreamLine("FL=%d FR=%d BL=%d BR=%d", fl, fr, bl, br);

    if (!fl || !fr || !bl || !br) {
      if (!fl && !fr && !bl && !br) {
        writeDebugStreamLine("Pattern: all sensors on line.");
      } else if (!fl && !fr) {
        writeDebugStreamLine("Pattern: front pair on line.");
      } else if (!bl && !br) {
        writeDebugStreamLine("Pattern: back pair on line.");
      } else if ((!fl || !bl) && (!fr || !br)) {
        writeDebugStreamLine("Pattern: left+right sides on line (corner/diagonal).");
      } else if (!fl || !bl) {
        writeDebugStreamLine("Pattern: left side on line.");
      } else {
        writeDebugStreamLine("Pattern: right side on line.");
      }
    }

    wait1Msec(120);
  }
}



