#pragma config(Sensor, in5,    centerLight,    sensorAnalog)
#pragma config(Sensor, in6,    backLight,      sensorAnalog)
#pragma config(Sensor, in7,    frontUpperLight, sensorAnalog)
#pragma config(Sensor, in8,    frontBelowLight, sensorAnalog)
#pragma config(Sensor, dgtl1,  unusedD1,       sensorNone)
#pragma config(Sensor, dgtl2,  unusedD2,       sensorNone)
#pragma config(Sensor, dgtl3,  west,           sensorDigitalIn)
#pragma config(Sensor, dgtl4,  south,          sensorDigitalIn)
#pragma config(Sensor, dgtl5,  east,           sensorDigitalIn)
#pragma config(Sensor, dgtl6,  north,           sensorDigitalIn)
#pragma config(Sensor, dgtl9,  backRightLine,         sensorDigitalIn)
#pragma config(Sensor, dgtl10, backLeftLine,          sensorDigitalIn)
#pragma config(Sensor, dgtl11, frontRightLine,            sensorDigitalIn)
#pragma config(Sensor, dgtl12, frontLeftLine,            sensorDigitalIn)
#pragma config(Motor,  port6,           gateMotor,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           collectorMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightWheel,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftWheel,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  motor_test.c
  Runs each motor one by one so you can verify wiring and direction quickly.
*/



task main() {
  clearDebugStream();
  writeDebugStreamLine("Motor test started.");

  while (true) {

    wait1Msec(100);

   	motor[collectorMotor] = 127;
  }
}
