#pragma config(Sensor, in1,    frontBelowLight, sensorAnalog)
#pragma config(Sensor, in2,    frontUpperLight, sensorAnalog)
#pragma config(Sensor, in3,    centerLight,     sensorAnalog)
#pragma config(Sensor, in4,    backLight,       sensorAnalog)
#pragma config(Sensor, dgtl1,  frontLeftLine,   sensorDigitalIn)
#pragma config(Sensor, dgtl2,  frontRightLine,  sensorDigitalIn)
#pragma config(Sensor, dgtl3,  backLeftLine,    sensorDigitalIn)
#pragma config(Sensor, dgtl4,  backRightLine,   sensorDigitalIn)
#pragma config(Sensor, dgtl5,  unusedD5,        sensorNone)
#pragma config(Sensor, dgtl6,  unusedD6,        sensorNone)
#pragma config(Sensor, dgtl7,  unusedD7,        sensorNone)
#pragma config(Sensor, dgtl8,  unusedD8,        sensorNone)
#pragma config(Sensor, dgtl9,  compassLSB,      sensorDigitalIn)
#pragma config(Sensor, dgtl10, compassBit1,     sensorDigitalIn)
#pragma config(Sensor, dgtl11, compassBit2,     sensorDigitalIn)
#pragma config(Sensor, dgtl12, compassMSB,      sensorDigitalIn)
#pragma config(Motor,  port1,  rightWheel,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port2,  leftWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,  collectorMotor,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,  gateMotor,       tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



/*
  motor_test.c
  Runs each motor one by one so you can verify wiring and direction quickly.
*/

const int DRIVE_TEST_POWER = 90;
const int AUX_TEST_POWER = 100;
const int TEST_DURATION_MS = 1200;
const int PAUSE_MS = 400;

void setDrive(int leftPower, int rightPower) {
  motor[leftWheel] = leftPower;
  motor[rightWheel] = rightPower;
}

void stopAllMotors() {
  motor[leftWheel] = 0;
  motor[rightWheel] = 0;
  motor[collectorMotor] = 0;
  motor[gateMotor] = 0;
}

task main() {
  clearDebugStream();
  writeDebugStreamLine("Motor test started.");

  while (true) {
    stopAllMotors();
    wait1Msec(PAUSE_MS);

    writeDebugStreamLine("Right wheel forward.");
    motor[rightWheel] = DRIVE_TEST_POWER;
    wait1Msec(TEST_DURATION_MS);
    motor[rightWheel] = 0;

    writeDebugStreamLine("Right wheel backward.");
    motor[rightWheel] = -DRIVE_TEST_POWER;
    wait1Msec(TEST_DURATION_MS);
    motor[rightWheel] = 0;

    wait1Msec(PAUSE_MS);

    writeDebugStreamLine("Left wheel forward.");
    motor[leftWheel] = DRIVE_TEST_POWER;
    wait1Msec(TEST_DURATION_MS);
    motor[leftWheel] = 0;

    writeDebugStreamLine("Left wheel backward.");
    motor[leftWheel] = -DRIVE_TEST_POWER;
    wait1Msec(TEST_DURATION_MS);
    motor[leftWheel] = 0;

    wait1Msec(PAUSE_MS);

    writeDebugStreamLine("Both wheels forward.");
    setDrive(DRIVE_TEST_POWER, DRIVE_TEST_POWER);
    wait1Msec(TEST_DURATION_MS);
    stopAllMotors();

    writeDebugStreamLine("Both wheels backward.");
    setDrive(-DRIVE_TEST_POWER, -DRIVE_TEST_POWER);
    wait1Msec(TEST_DURATION_MS);
    stopAllMotors();

    wait1Msec(PAUSE_MS);

    writeDebugStreamLine("Collector motor spin.");
    motor[collectorMotor] = AUX_TEST_POWER;
    wait1Msec(TEST_DURATION_MS);
    motor[collectorMotor] = 0;

    writeDebugStreamLine("Collector motor reverse.");
    motor[collectorMotor] = -AUX_TEST_POWER;
    wait1Msec(TEST_DURATION_MS);
    motor[collectorMotor] = 0;

    wait1Msec(PAUSE_MS);

    writeDebugStreamLine("Gate motor open direction.");
    motor[gateMotor] = AUX_TEST_POWER;
    wait1Msec(TEST_DURATION_MS);
    motor[gateMotor] = 0;

    writeDebugStreamLine("Gate motor close direction.");
    motor[gateMotor] = -AUX_TEST_POWER;
    wait1Msec(TEST_DURATION_MS);
    motor[gateMotor] = 0;

    writeDebugStreamLine("Motor test cycle complete. Repeating...");
    wait1Msec(1000);
  }
}
