#pragma config(Sensor, in5,    centerLight,    sensorAnalog)
#pragma config(Sensor, in6,    backLight,      sensorAnalog)
#pragma config(Sensor, in7,    frontUpperLight, sensorAnalog)
#pragma config(Sensor, in8,    frontBelowLight, sensorAnalog)
#pragma config(Sensor, dgtl1,  unusedD1,       sensorNone)
#pragma config(Sensor, dgtl2,  unusedD2,       sensorNone)
#pragma config(Sensor, dgtl3,  west,           sensorDigitalIn)
#pragma config(Sensor, dgtl4,  south,          sensorDigitalIn)
#pragma config(Sensor, dgtl5,  east,           sensorDigitalIn)
#pragma config(Sensor, dgtl6,  noth,           sensorDigitalIn)
#pragma config(Sensor, dgtl7,  unusedD7,       sensorNone)
#pragma config(Sensor, dgtl8,  unusedD8,       sensorNone)
#pragma config(Sensor, dgtl9,  yellow,         sensorDigitalOut)
#pragma config(Sensor, dgtl10, green,          sensorDigitalOut)
#pragma config(Sensor, dgtl11, red,            sensorDigitalOut)
#pragma config(Motor,  port6,           gateMotor,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           collectorMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightWheel,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftWheel,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  west_alignment_test.c
  Wheel-based heading alignment test to WEST using active-low compass input.
*/

const int ALIGN_POWER = 60;
const int ALIGN_TIMEOUT_MS = 5000;
const int POST_ALIGN_HOLD_MS = 800;
const int REPEAT_FOREVER = 1;      // 1 = keep testing, 0 = one-shot.
const int USE_CCW_ALIGNMENT = 1;   // 1 = rotate CCW to WEST, 0 = rotate CW to WEST.

void setDrive(int leftPower, int rightPower) {
  motor[leftWheel] = leftPower;
  motor[rightWheel] = rightPower;
}

void stopAll() {
  motor[leftWheel] = 0;
  motor[rightWheel] = 0;
  motor[collectorMotor] = 0;
  motor[gateMotor] = 0;
}

void rotateCCW(int power) {
  setDrive(-power, power);
}

void rotateCW(int power) {
  setDrive(power, -power);
}

int isFacingWest() {
  // Strict WEST condition:
  // WEST must be active-low (0), and all other directions must be inactive (1).
  return (SensorValue[west] == 0 &&
          SensorValue[south] == 1 &&
          SensorValue[east] == 1 &&
          SensorValue[noth] == 1);
}

int alignToWest(int timeoutMs) {
  int startTime = nSysTime;

  while ((nSysTime - startTime) < timeoutMs) {
    if (isFacingWest()) {
      stopAll();
      return 1;
    }

    if (USE_CCW_ALIGNMENT) {
      rotateCCW(ALIGN_POWER);
    } else {
      rotateCW(ALIGN_POWER);
    }
    wait1Msec(20);
  }

  stopAll();
  return 0;
}

task main() {
  int ok = 0;

  clearDebugStream();
  writeDebugStreamLine("West alignment test started.");

  while (true) {
    writeDebugStreamLine(
      "Compass raw W/S/E/N = %d/%d/%d/%d",
      SensorValue[west], SensorValue[south], SensorValue[east], SensorValue[noth]
    );

    if (isFacingWest()) {
      writeDebugStreamLine("Already facing WEST.");
      stopAll();
    } else {
      writeDebugStreamLine("Aligning to WEST...");
      ok = alignToWest(ALIGN_TIMEOUT_MS);
      if (ok) {
        writeDebugStreamLine("Alignment success: WEST detected.");
      } else {
        writeDebugStreamLine("Alignment timeout: WEST not detected.");
      }
    }

    wait1Msec(POST_ALIGN_HOLD_MS);

    if (!REPEAT_FOREVER) {
      writeDebugStreamLine("West alignment test completed (single run).");
      break;
    }
  }
}
