#pragma config(Sensor, in4,    frontBelowLight, sensorAnalog)
#pragma config(Sensor, in3,    frontUpperLight, sensorAnalog)
#pragma config(Sensor, in2,    centerLight,     sensorAnalog)
#pragma config(Sensor, in1,    backLight,       sensorAnalog)
#pragma config(Sensor, dgtl12,  frontLeftLine,   sensorDigitalIn)
#pragma config(Sensor, dgtl11,  frontRightLine,  sensorDigitalIn)
#pragma config(Sensor, dgtl10,  backLeftLine,    sensorDigitalIn)
#pragma config(Sensor, dgtl9,  backRightLine,   sensorDigitalIn)
#pragma config(Sensor, dgtl1,  unusedD1,        sensorNone)
#pragma config(Sensor, dgtl2,  unusedD2,        sensorNone)
#pragma config(Sensor, dgtl7,  unusedD7,        sensorNone)
#pragma config(Sensor, dgtl8,  unusedD8,        sensorNone)
#pragma config(Sensor, dgtl3,  west,      sensorDigitalIn)
#pragma config(Sensor, dgtl4,  south,     sensorDigitalIn)
#pragma config(Sensor, dgtl5,  east,     sensorDigitalIn)
#pragma config(Sensor, dgtl6,  noth,      sensorDigitalIn)
#pragma config(Motor,  port6,           gateMotor,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           collectorMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightWheel,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftWheel,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



/*
  ball_collection_test.c
  3-phase robust cycle:
  SEARCHING -> COLLECTING -> DEPOSITING -> reset back to SEARCHING
*/

const int FRONT_LOWER_BALL_MIN = 900;
const int FRONT_UPPER_BALL_MAX = 900;
const int CENTER_BALL_COLLECT_MIN = 1300;
const int BACK_STABLE_FLUCT_LIMIT = 300;

const int SEARCH_FORWARD_MS = 1000;
const int SEARCH_MAX_CYCLES = 4;
const int SEARCH_ALIGN_TIMEOUT_MS = 5000;

const int COLLECT_TIMEOUT_MS = 3000;

const int DEPOSIT_INITIAL_REVERSE_MS = 4000;
const int DEPOSIT_STEP_REVERSE_MS = 1000;
const int DEPOSIT_TIMEOUT_MS = 10000;
const int DEPOSIT_STABILITY_SAMPLE_MS = 400;
const int DEPOSIT_SETTLE_MS = 120;

const int DRIVE_FORWARD_POWER = 85;
const int DRIVE_COLLECT_POWER = 90;
const int DRIVE_REVERSE_POWER = 80;
const int DRIVE_TURN_POWER = 60;
const int COLLECTOR_POWER = 127;

const int PHASE_SEARCHING = 0;
const int PHASE_COLLECTING = 1;
const int PHASE_DEPOSITING = 2;

int searchLowerTriggered = 0;
int searchLowerPeak = 0;
int searchLowerSum = 0;
int searchLowerSamples = 0;

void setDrive(int leftPower, int rightPower) {
  motor[leftWheel] = leftPower;
  motor[rightWheel] = rightPower;
}

void stopDrive() {
  setDrive(0, 0);
}

void turnLeftInPlace(int power) {
  setDrive(-power, power);
}

void turnRightInPlace(int power) {
  setDrive(power, -power);
}

int isBallCandidate() {
  int lower = SensorValue[frontBelowLight];
  int upper = SensorValue[frontUpperLight];
  return (lower > FRONT_LOWER_BALL_MIN &&
          upper < FRONT_UPPER_BALL_MAX);
}

int isFrontLowerTriggered() {
  return SensorValue[frontBelowLight] > FRONT_LOWER_BALL_MIN;
}

int isBallCollectedAtCenter() {
  return SensorValue[centerLight] > CENTER_BALL_COLLECT_MIN;
}

int isFacingWest() {
  // Strict WEST condition:
  // WEST must be active-low (0), and all other directions must be inactive (1).
  return (SensorValue[west] == 0 &&
          SensorValue[south] == 1 &&
          SensorValue[east] == 1 &&
          SensorValue[noth] == 1);
}

void resetSearchLowerTracking() {
  searchLowerTriggered = 0;
  searchLowerPeak = 0;
  searchLowerSum = 0;
  searchLowerSamples = 0;
}

void updateSearchLowerTracking() {
  int lower = SensorValue[frontBelowLight];
  if (lower > searchLowerPeak) searchLowerPeak = lower;
  searchLowerSum += lower;
  searchLowerSamples++;
  if (isFrontLowerTriggered()) searchLowerTriggered = 1;
}

int runForwardAndCheckBall(int durationMs) {
  int startTime = nSysTime;
  while ((nSysTime - startTime) < durationMs) {
    updateSearchLowerTracking();
    if (isBallCandidate()) {
      stopDrive();
      return 1;
    }
    setDrive(DRIVE_FORWARD_POWER, DRIVE_FORWARD_POWER);
    wait1Msec(20);
  }
  stopDrive();
  return 0;
}

int rotateCCWToWestAndCheckBall(int timeoutMs) {
  int startTime = nSysTime;
  while ((nSysTime - startTime) < timeoutMs) {
    updateSearchLowerTracking();
    if (isBallCandidate()) {
      stopDrive();
      return 1;
    }
    if (isFacingWest()) {
      stopDrive();
      return 0;
    }
    turnLeftInPlace(DRIVE_TURN_POWER);
    wait1Msec(20);
  }
  stopDrive();
  return 0;
}

void alignToWestCCW(int timeoutMs) {
  int startTime = nSysTime;
  while ((nSysTime - startTime) < timeoutMs && !isFacingWest()) {
    turnLeftInPlace(DRIVE_TURN_POWER);
    wait1Msec(20);
  }
  stopDrive();
}

void reverseKeepingWest(int durationMs) {
  int startTime = nSysTime;
  while ((nSysTime - startTime) < durationMs) {
    if (isFacingWest()) {
      setDrive(-DRIVE_REVERSE_POWER, -DRIVE_REVERSE_POWER);
    } else {
      turnLeftInPlace(DRIVE_TURN_POWER);
    }
    wait1Msec(20);
  }
  stopDrive();
}

int measureBackSensorFluctuation(int sampleMs) {
  int startTime = nSysTime;
  int minVal = 4095;
  int maxVal = 0;
  int value = 0;

  while ((nSysTime - startTime) < sampleMs) {
    value = SensorValue[backLight];
    if (value < minVal) minVal = value;
    if (value > maxVal) maxVal = value;
    wait1Msec(20);
  }

  return (maxVal - minVal);
}

int checkBackStabilityAfterCycle() {
  // Important: sample only after reverse motion has fully stopped.
  stopDrive();
  wait1Msec(DEPOSIT_SETTLE_MS);
  return measureBackSensorFluctuation(DEPOSIT_STABILITY_SAMPLE_MS);
}

int runSearchingPhase() {
  int cycle = 0;
  for (cycle = 0; cycle < SEARCH_MAX_CYCLES; cycle++) {
    resetSearchLowerTracking();
    writeDebugStreamLine("SEARCH cycle %d/%d", cycle + 1, SEARCH_MAX_CYCLES);

    if (runForwardAndCheckBall(SEARCH_FORWARD_MS)) {
      writeDebugStreamLine("Ball detected during forward search.");
      return PHASE_COLLECTING;
    }

    if (rotateCCWToWestAndCheckBall(SEARCH_ALIGN_TIMEOUT_MS)) {
      writeDebugStreamLine("Ball detected while aligning to WEST.");
      return PHASE_COLLECTING;
    }

    if (searchLowerSamples > 0) {
      writeDebugStreamLine(
        "SEARCH lower-tracking: triggered=%d peak=%d avg=%d",
        searchLowerTriggered,
        searchLowerPeak,
        (searchLowerSum / searchLowerSamples)
      );
    }
  }

  writeDebugStreamLine("SEARCH completed 4 cycles with no ball. Go DEPOSIT.");
  return PHASE_DEPOSITING;
}

int runCollectingPhase() {
  int startTime = nSysTime;
  writeDebugStreamLine("COLLECTING started.");

  // Immediate handoff: if ball is already inside, skip collect motion and deposit now.
  if (isBallCollectedAtCenter()) {
    stopDrive();
    writeDebugStreamLine("COLLECTING immediate success. Go DEPOSIT now.");
    return PHASE_DEPOSITING;
  }

  while ((nSysTime - startTime) < COLLECT_TIMEOUT_MS) {
    if (isBallCollectedAtCenter()) {
      stopDrive();
      writeDebugStreamLine("COLLECTING success before timeout. Go DEPOSIT.");
      return PHASE_DEPOSITING;
    }

    setDrive(DRIVE_COLLECT_POWER, DRIVE_COLLECT_POWER);
    wait1Msec(20);
  }

  stopDrive();
  writeDebugStreamLine("COLLECTING timeout (3s). Reset to SEARCH.");
  return PHASE_SEARCHING;
}

int runDepositingPhase() {
  int phaseStart = nSysTime;
  int fluctuation = 0;
  int depositCycle = 1;

  writeDebugStreamLine("DEPOSITING started.");
  alignToWestCCW(SEARCH_ALIGN_TIMEOUT_MS);
  reverseKeepingWest(DEPOSIT_INITIAL_REVERSE_MS);

  while ((nSysTime - phaseStart) < DEPOSIT_TIMEOUT_MS) {
    fluctuation = checkBackStabilityAfterCycle();
    writeDebugStreamLine(
      "DEPOSIT cycle %d check: back fluctuation = %d",
      depositCycle,
      fluctuation
    );

    if (fluctuation <= BACK_STABLE_FLUCT_LIMIT) {
      writeDebugStreamLine("DEPOSIT stable back sensor. Reset to SEARCH.");
      return PHASE_SEARCHING;
    }

    alignToWestCCW(SEARCH_ALIGN_TIMEOUT_MS);
    reverseKeepingWest(DEPOSIT_STEP_REVERSE_MS);
    depositCycle++;
  }

  stopDrive();
  writeDebugStreamLine("DEPOSIT timeout (10s). Forced reset to SEARCH.");
  return PHASE_SEARCHING;
}

task main() {
  int phase = PHASE_SEARCHING;

  clearDebugStream();
  writeDebugStreamLine("Ball collection state-machine test started.");

  while (true) {
    motor[collectorMotor] = COLLECTOR_POWER;

    if (phase == PHASE_SEARCHING) {
      phase = runSearchingPhase();
    } else if (phase == PHASE_COLLECTING) {
      phase = runCollectingPhase();
    } else {
      phase = runDepositingPhase();
    }

    stopDrive();
    wait1Msec(80);
  }
}
