#pragma config(Sensor, in1,    backLight,      sensorAnalog)
#pragma config(Sensor, in2,    centerLight,    sensorAnalog)
#pragma config(Sensor, in3,    frontUpperLight, sensorAnalog)
#pragma config(Sensor, in4,    frontBelowLight, sensorAnalog)
#pragma config(Sensor, dgtl1,  unusedD1,       sensorNone)
#pragma config(Sensor, dgtl2,  unusedD2,       sensorNone)
#pragma config(Sensor, dgtl3,  west,           sensorDigitalIn)
#pragma config(Sensor, dgtl4,  south,          sensorDigitalIn)
#pragma config(Sensor, dgtl5,  east,           sensorDigitalIn)
#pragma config(Sensor, dgtl6,  noth,           sensorDigitalIn)
#pragma config(Sensor, dgtl7,  unusedD7,       sensorNone)
#pragma config(Sensor, dgtl8,  unusedD8,       sensorNone)
#pragma config(Sensor, dgtl9,  backRightLine,  sensorDigitalIn)
#pragma config(Sensor, dgtl10, backLeftLine,   sensorDigitalIn)
#pragma config(Sensor, dgtl11, frontRightLine, sensorDigitalIn)
#pragma config(Sensor, dgtl12, frontLeftLine,  sensorDigitalIn)
#pragma config(Motor,  port6,           gateMotor,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           collectorMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightWheel,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftWheel,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  ball_collection_forward_only_test.c
  Forward-only collection test:
  drive forward continuously while collector motor runs.
  No light-sensor logic is used.
*/

const int FORWARD_POWER = 50;
const int COLLECTOR_POWER = 120;


void setDrive(int leftPower, int rightPower) {
  motor[leftWheel] = leftPower;
  motor[rightWheel] = rightPower;
}

task main() {
  clearDebugStream();
  writeDebugStreamLine("Forward-only ball collection test started.");

  motor[collectorMotor] = COLLECTOR_POWER;
  setDrive(FORWARD_POWER, FORWARD_POWER);

  while (true) {
    wait1Msec(25);
  }
}
