#pragma config(Sensor, in4,    frontBelowLight, sensorAnalog)
#pragma config(Sensor, in3,    frontUpperLight, sensorAnalog)
#pragma config(Sensor, in2,    centerLight,     sensorAnalog)
#pragma config(Sensor, in1,    backLight,       sensorAnalog)
#pragma config(Sensor, dgtl12,  frontLeftLine,   sensorDigitalIn)
#pragma config(Sensor, dgtl11,  frontRightLine,  sensorDigitalIn)
#pragma config(Sensor, dgtl10,  backLeftLine,    sensorDigitalIn)
#pragma config(Sensor, dgtl9,  backRightLine,   sensorDigitalIn)
#pragma config(Sensor, dgtl1,  unusedD1,        sensorNone)
#pragma config(Sensor, dgtl2,  unusedD2,        sensorNone)
#pragma config(Sensor, dgtl7,  unusedD7,        sensorNone)
#pragma config(Sensor, dgtl8,  unusedD8,        sensorNone)
#pragma config(Sensor, dgtl3,  west,      sensorDigitalIn)
#pragma config(Sensor, dgtl4,  south,     sensorDigitalIn)
#pragma config(Sensor, dgtl5,  east,     sensorDigitalIn)
#pragma config(Sensor, dgtl6,  noth,      sensorDigitalIn)
#pragma config(Motor,  port6,           gateMotor,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           collectorMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightWheel,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftWheel,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



/*
  ball_collection_test.c
  Detects ball candidate -> approach while collector spins -> stop when center sensor says ball is inside.
*/

const int FRONT_BELOW_BALL_MIN = 1400;
const int FRONT_BELOW_BALL_MAX = 3600;
const int FRONT_UPPER_OBSTACLE_MIN = 1200;
const int CENTER_BALL_COLLECT_MIN = 1200;

const int DRIVE_APPROACH_POWER = 95;
const int DRIVE_CREEP_POWER = 65;
const int DRIVE_SCAN_POWER = 55;
const int DRIVE_AVOID_POWER = 75;
const int INITIAL_BALL_SEARCH_TIMEOUT_MS = 1800;
const int INITIAL_BALL_CONFIRM_COUNT = 2;
const int DRIVE_BOUNDARY_REVERSE_POWER = 85;
const int DRIVE_BOUNDARY_REVERSE_MS = 1500;
const int BOUNDARY_ALIGN_TURN_POWER = 55;
const int COLLECTOR_POWER = 127;

void setDrive(int leftPower, int rightPower) {
  motor[leftWheel] = leftPower;
  motor[rightWheel] = rightPower;
}

void stopDrive() {
  setDrive(0, 0);
}

void turnLeftInPlace(int power) {
  setDrive(-power, power);
}

void turnRightInPlace(int power) {
  setDrive(power, -power);
}

int readCompassDirectionIndex() {
  // Compass outputs are active-low: 0 means that direction is active.
  if (SensorValue[noth] == 0) return 0; // N
  if (SensorValue[east] == 0) return 1; // E
  if (SensorValue[south] == 0) return 2; // S
  if (SensorValue[west] == 0) return 3; // W
  return -1;
}

int anyLineDetected() {
  return (SensorValue[frontLeftLine] == 0 ||
          SensorValue[frontRightLine] == 0 ||
          SensorValue[backLeftLine] == 0 ||
          SensorValue[backRightLine] == 0);
}

int isBallCandidate() {
  int lower = SensorValue[frontBelowLight];
  int upper = SensorValue[frontUpperLight];
  return (lower >= FRONT_BELOW_BALL_MIN &&
          lower <= FRONT_BELOW_BALL_MAX &&
          upper < FRONT_UPPER_OBSTACLE_MIN);
}

int isObstacleCandidate() {
  return SensorValue[frontUpperLight] >= FRONT_UPPER_OBSTACLE_MIN;
}

int isBallCollectedAtCenter() {
  return SensorValue[centerLight] > CENTER_BALL_COLLECT_MIN;
}

void recoverFromBoundary() {
  int currentHeading = -1;

  // Requested behavior: reverse first to clear the corner before rotating.
  setDrive(-DRIVE_BOUNDARY_REVERSE_POWER, -DRIVE_BOUNDARY_REVERSE_POWER);
  wait1Msec(DRIVE_BOUNDARY_REVERSE_MS);

  while (true) {
    if (SensorValue[west] == 0) {
      break;
    }

    currentHeading = readCompassDirectionIndex();
    if (currentHeading < 0) {
      turnRightInPlace(BOUNDARY_ALIGN_TURN_POWER);
      wait1Msec(40);
      continue;
    } else if (currentHeading == 3) {
      break;
    } else {
      // Simple constant rotation until WEST is detected.
      turnRightInPlace(BOUNDARY_ALIGN_TURN_POWER);
    }

    wait1Msec(40);
  }

  stopDrive();
  wait1Msec(120);
}

int acquireInitialBallTarget(int timeoutMs) {
  int startTime = nSysTime;
  int confirmCount = 0;

  while ((nSysTime - startTime) < timeoutMs) {
    if (isBallCollectedAtCenter()) {
      stopDrive();
      return 1;
    }

    if (anyLineDetected()) {
      recoverFromBoundary();
      continue;
    }

    if (isBallCandidate()) {
      confirmCount++;
      if (confirmCount >= INITIAL_BALL_CONFIRM_COUNT) {
        stopDrive();
        return 1;
      }
    } else {
      confirmCount = 0;
    }

    if (isObstacleCandidate()) {
      setDrive(-DRIVE_CREEP_POWER, -DRIVE_CREEP_POWER);
      wait1Msec(140);
      turnRightInPlace(DRIVE_AVOID_POWER);
      wait1Msec(170);
      continue;
    }

    // Initial detection mechanism: rotate and search until a valid ball candidate is found.
    turnLeftInPlace(DRIVE_SCAN_POWER);
    wait1Msec(25);
  }

  stopDrive();
  return 0;
}

int runBallCollection(int timeoutMs) {
  int startTime = nSysTime;
  int lastBallSeen = nSysTime - 1000;

  motor[collectorMotor] = COLLECTOR_POWER;
  if (acquireInitialBallTarget(INITIAL_BALL_SEARCH_TIMEOUT_MS)) {
    writeDebugStreamLine("Initial ball lock acquired.");
    lastBallSeen = nSysTime;
  } else {
    writeDebugStreamLine("Initial ball lock not found, continue scanning.");
  }

  while ((nSysTime - startTime) < timeoutMs) {
    if (isBallCollectedAtCenter()) {
      stopDrive();
      writeDebugStreamLine("Collection success: center sensor triggered.");
      return 1;
    }

    if (anyLineDetected()) {
      writeDebugStreamLine("Boundary detected during collection. Recovering...");
      recoverFromBoundary();
      continue;
    }

    if (isBallCandidate()) {
      lastBallSeen = nSysTime;
      setDrive(DRIVE_APPROACH_POWER, DRIVE_APPROACH_POWER);
    } else if (isObstacleCandidate()) {
      setDrive(-DRIVE_CREEP_POWER, -DRIVE_CREEP_POWER);
      wait1Msec(180);
      turnRightInPlace(DRIVE_AVOID_POWER);
      wait1Msec(220);
    } else if ((nSysTime - lastBallSeen) < 250) {
      setDrive(DRIVE_CREEP_POWER, DRIVE_CREEP_POWER);
    } else {
      turnLeftInPlace(DRIVE_SCAN_POWER);
    }

    wait1Msec(25);
  }

  stopDrive();
  writeDebugStreamLine("Collection timeout.");
  return 0;
}

task main() {
  clearDebugStream();
  writeDebugStreamLine("Ball collection test started.");

  while (true) {
    int success = runBallCollection(12000);
    stopDrive();

    if (success) {
      writeDebugStreamLine("Result: BALL COLLECTED.");
    } else {
      writeDebugStreamLine("Result: FAILED OR TIMEOUT.");
    }

    wait1Msec(1200);
  }
}



