#pragma config(Sensor, in1,    frontBelowLight, sensorAnalog)
#pragma config(Sensor, in2,    frontUpperLight, sensorAnalog)
#pragma config(Sensor, in3,    centerLight,     sensorAnalog)
#pragma config(Sensor, in4,    backLight,       sensorAnalog)
#pragma config(Sensor, dgtl1,  frontLeftLine,   sensorDigitalIn)
#pragma config(Sensor, dgtl2,  frontRightLine,  sensorDigitalIn)
#pragma config(Sensor, dgtl3,  backLeftLine,    sensorDigitalIn)
#pragma config(Sensor, dgtl4,  backRightLine,   sensorDigitalIn)
#pragma config(Sensor, dgtl5,  unusedD5,        sensorNone)
#pragma config(Sensor, dgtl6,  unusedD6,        sensorNone)
#pragma config(Sensor, dgtl7,  unusedD7,        sensorNone)
#pragma config(Sensor, dgtl8,  unusedD8,        sensorNone)
#pragma config(Sensor, dgtl9,  compassLSB,      sensorDigitalIn)
#pragma config(Sensor, dgtl10, compassBit1,     sensorDigitalIn)
#pragma config(Sensor, dgtl11, compassBit2,     sensorDigitalIn)
#pragma config(Sensor, dgtl12, compassMSB,      sensorDigitalIn)
#pragma config(Motor,  port1,  rightWheel,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port2,  leftWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,  collectorMotor,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,  gateMotor,       tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



/*
  ball_collection_test.c
  Detects ball candidate -> approach while collector spins -> stop when center sensor says ball is inside.
*/

const int FRONT_BELOW_BALL_MIN = 1400;
const int FRONT_BELOW_BALL_MAX = 3600;
const int FRONT_UPPER_OBSTACLE_MIN = 1200;
const int CENTER_BALL_INSIDE_MIN = 1600;

const int DRIVE_APPROACH_POWER = 95;
const int DRIVE_CREEP_POWER = 65;
const int DRIVE_SCAN_POWER = 55;
const int DRIVE_AVOID_POWER = 75;
const int DRIVE_BOUNDARY_REVERSE_POWER = 90;
const int DRIVE_BOUNDARY_TURN_POWER = 80;
const int COLLECTOR_POWER = 127;

int boundaryTurnRight = 1;

void setDrive(int leftPower, int rightPower) {
  motor[leftWheel] = leftPower;
  motor[rightWheel] = rightPower;
}

void stopDrive() {
  setDrive(0, 0);
}

void turnLeftInPlace(int power) {
  setDrive(-power, power);
}

void turnRightInPlace(int power) {
  setDrive(power, -power);
}

int anyLineDetected() {
  return (SensorValue[frontLeftLine] ||
          SensorValue[frontRightLine] ||
          SensorValue[backLeftLine] ||
          SensorValue[backRightLine]);
}

int isBallCandidate() {
  int lower = SensorValue[frontBelowLight];
  int upper = SensorValue[frontUpperLight];
  return (lower >= FRONT_BELOW_BALL_MIN &&
          lower <= FRONT_BELOW_BALL_MAX &&
          upper < FRONT_UPPER_OBSTACLE_MIN);
}

int isObstacleCandidate() {
  return SensorValue[frontUpperLight] >= FRONT_UPPER_OBSTACLE_MIN;
}

int isBallCollectedAtCenter() {
  return SensorValue[centerLight] >= CENTER_BALL_INSIDE_MIN;
}

void recoverFromBoundary() {
  int fl = SensorValue[frontLeftLine];
  int fr = SensorValue[frontRightLine];
  int bl = SensorValue[backLeftLine];
  int br = SensorValue[backRightLine];

  setDrive(-DRIVE_BOUNDARY_REVERSE_POWER, -DRIVE_BOUNDARY_REVERSE_POWER);
  wait1Msec(350);

  if ((fl && fr) || (bl && br) || ((fl || bl) && (fr || br))) {
    if (boundaryTurnRight) {
      turnRightInPlace(DRIVE_BOUNDARY_TURN_POWER);
    } else {
      turnLeftInPlace(DRIVE_BOUNDARY_TURN_POWER);
    }
    boundaryTurnRight = !boundaryTurnRight;
    wait1Msec(420);
  } else if (fl || bl) {
    turnRightInPlace(DRIVE_BOUNDARY_TURN_POWER);
    wait1Msec(320);
  } else if (fr || br) {
    turnLeftInPlace(DRIVE_BOUNDARY_TURN_POWER);
    wait1Msec(320);
  }

  stopDrive();
  wait1Msec(120);
}

int runBallCollection(int timeoutMs) {
  int startTime = nSysTime;
  int lastBallSeen = nSysTime;

  motor[collectorMotor] = COLLECTOR_POWER;

  while ((nSysTime - startTime) < timeoutMs) {
    if (isBallCollectedAtCenter()) {
      stopDrive();
      writeDebugStreamLine("Collection success: center sensor triggered.");
      return 1;
    }

    if (anyLineDetected()) {
      writeDebugStreamLine("Boundary detected during collection. Recovering...");
      recoverFromBoundary();
      continue;
    }

    if (isBallCandidate()) {
      lastBallSeen = nSysTime;
      setDrive(DRIVE_APPROACH_POWER, DRIVE_APPROACH_POWER);
    } else if (isObstacleCandidate()) {
      setDrive(-DRIVE_CREEP_POWER, -DRIVE_CREEP_POWER);
      wait1Msec(180);
      turnRightInPlace(DRIVE_AVOID_POWER);
      wait1Msec(220);
    } else if ((nSysTime - lastBallSeen) < 250) {
      setDrive(DRIVE_CREEP_POWER, DRIVE_CREEP_POWER);
    } else {
      turnLeftInPlace(DRIVE_SCAN_POWER);
    }

    wait1Msec(25);
  }

  stopDrive();
  writeDebugStreamLine("Collection timeout.");
  return 0;
}

task main() {
  clearDebugStream();
  writeDebugStreamLine("Ball collection test started.");

  while (true) {
    int success = runBallCollection(12000);
    stopDrive();

    if (success) {
      writeDebugStreamLine("Result: BALL COLLECTED.");
    } else {
      writeDebugStreamLine("Result: FAILED OR TIMEOUT.");
    }

    wait1Msec(1200);
  }
}
