#pragma config(Sensor, in5,    centerLight,    sensorAnalog)
#pragma config(Sensor, in6,    backLight,      sensorAnalog)
#pragma config(Sensor, in7,    frontUpperLight, sensorAnalog)
#pragma config(Sensor, in8,    frontBelowLight, sensorAnalog)
#pragma config(Sensor, dgtl1,  unusedD1,       sensorNone)
#pragma config(Sensor, dgtl2,  unusedD2,       sensorNone)
#pragma config(Sensor, dgtl3,  west,           sensorDigitalIn)
#pragma config(Sensor, dgtl4,  south,          sensorDigitalIn)
#pragma config(Sensor, dgtl5,  east,           sensorDigitalIn)
#pragma config(Sensor, dgtl6,  noth,           sensorDigitalIn)
#pragma config(Sensor, dgtl7,  unusedD7,       sensorNone)
#pragma config(Sensor, dgtl8,  unusedD8,       sensorNone)
#pragma config(Sensor, dgtl9,  yellow,         sensorDigitalOut)
#pragma config(Sensor, dgtl10, green,          sensorDigitalOut)
#pragma config(Sensor, dgtl11, red,            sensorDigitalOut)
#pragma config(Motor,  port6,           gateMotor,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           collectorMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightWheel,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftWheel,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Compatibility aliases: line sensors are not mapped in the standardized config.
#define frontLeftLine  unusedD1
#define frontRightLine unusedD2
#define backLeftLine   unusedD7
#define backRightLine  unusedD8



/*
  ball_deposit_test.c
  Align to East with compass, reverse to collection area, then open/close gate.
*/

const int CENTER_BALL_COLLECT_MIN = 1200;
const int BACK_DEPOSIT_TRIGGER_MIN = 2400;

const int ALIGN_TURN_POWER = 65;
const int REVERSE_POWER = 80;
const int REVERSE_CORRECT_POWER = 55;
const int GATE_OPEN_SPEED = 100;
const int GATE_CLOSE_SPEED = -100;
const int GATE_MOVE_MS = 550;

void setDrive(int leftPower, int rightPower) {
  motor[leftWheel] = leftPower;
  motor[rightWheel] = rightPower;
}

void stopDrive() {
  setDrive(0, 0);
}

void rotateCW(int power) {
  setDrive(power, -power);
}

void rotateCCW(int power) {
  setDrive(-power, power);
}

void openGate() {
  motor[gateMotor] = GATE_OPEN_SPEED;
  wait1Msec(GATE_MOVE_MS);
  motor[gateMotor] = 0;
}

void closeGate() {
  motor[gateMotor] = GATE_CLOSE_SPEED;
  wait1Msec(GATE_MOVE_MS);
  motor[gateMotor] = 0;
}

string headingFromIndex(int index) {
  switch (index) {
    case 0: return "N";
    case 1: return "E";
    case 2: return "S";
    case 3: return "W";
    default: return "UNKNOWN";
  }
}

int readCompassDirectionIndex() {
  // Compass outputs are active-low: 0 means that direction is active.
  if (SensorValue[noth] == 0) return 0; // N
  if (SensorValue[east] == 0) return 1; // E
  if (SensorValue[south] == 0) return 2; // S
  if (SensorValue[west] == 0) return 3; // W
  return -1;
}

int alignToEast(int timeoutMs) {
  int startTime = nSysTime;

  while ((nSysTime - startTime) < timeoutMs) {
    int currentHeading = readCompassDirectionIndex();
    if (currentHeading == 1) {
      stopDrive();
      return 1;
    }

    if (currentHeading < 0) {
      rotateCW(ALIGN_TURN_POWER);
      wait1Msec(80);
      continue;
    }

    // Shortest turn on 4-direction compass ring (N,E,S,W).
    int cwStepsToEast = (1 - currentHeading + 4) % 4;
    if (cwStepsToEast <= 2) {
      rotateCW(ALIGN_TURN_POWER);
    } else {
      rotateCCW(ALIGN_TURN_POWER);
    }
    wait1Msec(70);
  }

  stopDrive();
  return 0;
}

int reverseToCollection(int timeoutMs) {
  int startTime = nSysTime;

  while ((nSysTime - startTime) < timeoutMs) {
    int blHit = (SensorValue[backLeftLine] == 0);
    int brHit = (SensorValue[backRightLine] == 0);
    int backNear = (SensorValue[backLight] > BACK_DEPOSIT_TRIGGER_MIN);

    if (backNear) {
      stopDrive();
      return 1;
    }

    if (blHit && !brHit) {
      // Left side already close to line; bias to the right.
      setDrive(-REVERSE_CORRECT_POWER, -REVERSE_POWER);
    } else if (brHit && !blHit) {
      // Right side already close to line; bias to the left.
      setDrive(-REVERSE_POWER, -REVERSE_CORRECT_POWER);
    } else {
      setDrive(-REVERSE_POWER, -REVERSE_POWER);
    }

    wait1Msec(30);
  }

  stopDrive();
  return 0;
}

int runBallDepositRoutine() {
  int aligned = alignToEast(4500);
  if (!aligned) {
    writeDebugStreamLine("Deposit: failed to align East.");
    return 0;
  }

  writeDebugStreamLine("Deposit: aligned East.");
  writeDebugStreamLine("Heading now: %s", headingFromIndex(readCompassDirectionIndex()));

  if (!reverseToCollection(7000)) {
    writeDebugStreamLine("Deposit: failed to reach collection zone.");
    return 0;
  }

  stopDrive();
  writeDebugStreamLine("Deposit: reached collection zone. Opening gate...");
  openGate();
  wait1Msec(250);
  closeGate();

  // Move forward slightly after drop to clear the wall.
  setDrive(65, 65);
  wait1Msec(350);
  stopDrive();

  return 1;
}

task main() {
  clearDebugStream();
  writeDebugStreamLine("Ball deposit test started.");

  while (true) {
    int centerReady = (SensorValue[centerLight] > CENTER_BALL_COLLECT_MIN);
    writeDebugStreamLine("Center sensor says ball loaded: %d", centerReady);

    if (runBallDepositRoutine()) {
      writeDebugStreamLine("Result: DEPOSIT SUCCESS.");
    } else {
      writeDebugStreamLine("Result: DEPOSIT FAILED OR TIMEOUT.");
    }

    wait1Msec(1500);
  }
}


