#pragma config(Sensor, in8,    frontBelowLight, sensorAnalog)
#pragma config(Sensor, in3,    frontUpperLight, sensorAnalog)
#pragma config(Sensor, in2,    centerLight,     sensorAnalog)
#pragma config(Sensor, in1,    backLight,       sensorAnalog)
#pragma config(Sensor, dgtl12,  frontLeftLine,   sensorDigitalIn)
#pragma config(Sensor, dgtl11,  frontRightLine,  sensorDigitalIn)
#pragma config(Sensor, dgtl10,  backLeftLine,    sensorDigitalIn)
#pragma config(Sensor, dgtl9,  backRightLine,   sensorDigitalIn)
#pragma config(Sensor, dgtl1,  unusedD1,        sensorNone)
#pragma config(Sensor, dgtl2,  unusedD2,        sensorNone)
#pragma config(Sensor, dgtl7,  unusedD7,        sensorNone)
#pragma config(Sensor, dgtl8,  unusedD8,        sensorNone)
#pragma config(Sensor, dgtl3,  west,      sensorDigitalIn)
#pragma config(Sensor, dgtl4,  south,     sensorDigitalIn)
#pragma config(Sensor, dgtl5,  east,     sensorDigitalIn)
#pragma config(Sensor, dgtl6,  noth,      sensorDigitalIn)
#pragma config(Motor,  port6,           gateMotor,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           collectorMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightWheel,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftWheel,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  ball_collection_front_sensor_test.c
  Behavior:
  1) Rotate in place until frontBelowLight crosses threshold.
  2) Drive forward with collector running.
  3) Keep checking frontBelowLight; if lost for several cycles, go back to rotate-search.
  4) During forward approach, apply periodic right-turn nudges to counter left drift.
*/

const int FRONT_BELOW_DETECT_THRESHOLD = 1300;
const int FRONT_BELOW_LOST_THRESHOLD = 1000;
const int DETECT_CONFIRM_COUNT = 2;
const int LOST_CONFIRM_COUNT = 5;

const int SCAN_POWER = 45;
const int APPROACH_POWER = 75;
const int COLLECTOR_POWER = 127;

const int RIGHT_NUDGE_PERIOD_MS = 450;
const int RIGHT_NUDGE_POWER = 50;
const int RIGHT_NUDGE_MS = 80;
const int LOOP_DELAY_MS = 25;

const int STATE_SEARCH = 0;
const int STATE_APPROACH = 1;

void setDrive(int leftPower, int rightPower) {
  motor[leftWheel] = leftPower;
  motor[rightWheel] = rightPower;
}

void turnLeftInPlace(int power) {
  setDrive(-power, power);
}

void turnRightInPlace(int power) {
  setDrive(power, -power);
}

task main() {
  int state = STATE_SEARCH;
  int detectCount = 0;
  int lostCount = 0;
  int sensorReading = 0;
  int lastRightNudgeTime = nSysTime;

  clearDebugStream();
  writeDebugStreamLine("Front-sensor ball collection test started.");
  motor[collectorMotor] = COLLECTOR_POWER;

  while (true) {
    sensorReading = SensorValue[frontBelowLight];

    if (state == STATE_SEARCH) {
      if (sensorReading >= FRONT_BELOW_DETECT_THRESHOLD) {
        detectCount++;
      } else {
        detectCount = 0;
      }

      if (detectCount >= DETECT_CONFIRM_COUNT) {
        state = STATE_APPROACH;
        lostCount = 0;
        lastRightNudgeTime = nSysTime;
        writeDebugStreamLine("Target locked. Start approach. frontBelow=%d", sensorReading);
      } else {
        turnLeftInPlace(SCAN_POWER);
      }
    } else {
      if (sensorReading < FRONT_BELOW_LOST_THRESHOLD) {
        lostCount++;
      } else {
        lostCount = 0;
      }

      if (lostCount >= LOST_CONFIRM_COUNT) {
        state = STATE_SEARCH;
        detectCount = 0;
        writeDebugStreamLine("Target lost. Resume scan. frontBelow=%d", sensorReading);
      } else {
        // Keep moving forward, but nudge right periodically to counter left drift.
        if ((nSysTime - lastRightNudgeTime) >= RIGHT_NUDGE_PERIOD_MS) {
          turnRightInPlace(RIGHT_NUDGE_POWER);
          wait1Msec(RIGHT_NUDGE_MS);
          lastRightNudgeTime = nSysTime;
        }

        setDrive(APPROACH_POWER, APPROACH_POWER);
      }
    }

    wait1Msec(LOOP_DELAY_MS);
  }
}
