#pragma config(Sensor, in1,    frontBelowLight, sensorAnalog)
#pragma config(Sensor, in2,    frontUpperLight, sensorAnalog)
#pragma config(Sensor, in3,    centerLight,     sensorAnalog)
#pragma config(Sensor, in4,    backLight,       sensorAnalog)
#pragma config(Sensor, dgtl1,  frontLeftLine,   sensorDigitalIn)
#pragma config(Sensor, dgtl2,  frontRightLine,  sensorDigitalIn)
#pragma config(Sensor, dgtl3,  backLeftLine,    sensorDigitalIn)
#pragma config(Sensor, dgtl4,  backRightLine,   sensorDigitalIn)
#pragma config(Sensor, dgtl5,  unusedD5,        sensorNone)
#pragma config(Sensor, dgtl6,  unusedD6,        sensorNone)
#pragma config(Sensor, dgtl7,  unusedD7,        sensorNone)
#pragma config(Sensor, dgtl8,  unusedD8,        sensorNone)
#pragma config(Sensor, dgtl9,  compassLSB,      sensorDigitalIn)
#pragma config(Sensor, dgtl10, compassBit1,     sensorDigitalIn)
#pragma config(Sensor, dgtl11, compassBit2,     sensorDigitalIn)
#pragma config(Sensor, dgtl12, compassMSB,      sensorDigitalIn)
#pragma config(Motor,  port1,  rightWheel,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port2,  leftWheel,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,  collectorMotor,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,  gateMotor,       tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



/*
  ball_deposit_test.c
  Align to North with compass, reverse to collection area, then open/close gate.
*/

const int CENTER_BALL_INSIDE_MIN = 1600;
const int BACK_COLLECTION_NEAR_MIN = 1700;

const int ALIGN_TURN_POWER = 65;
const int REVERSE_POWER = 80;
const int REVERSE_CORRECT_POWER = 55;
const int GATE_OPEN_SPEED = 100;
const int GATE_CLOSE_SPEED = -100;
const int GATE_MOVE_MS = 550;

const int HEADING_NORTH = 0; // Index order: N,NE,E,SE,S,SW,W,NW

void setDrive(int leftPower, int rightPower) {
  motor[leftWheel] = leftPower;
  motor[rightWheel] = rightPower;
}

void stopDrive() {
  setDrive(0, 0);
}

void rotateCW(int power) {
  setDrive(power, -power);
}

void rotateCCW(int power) {
  setDrive(-power, power);
}

void openGate() {
  motor[gateMotor] = GATE_OPEN_SPEED;
  wait1Msec(GATE_MOVE_MS);
  motor[gateMotor] = 0;
}

void closeGate() {
  motor[gateMotor] = GATE_CLOSE_SPEED;
  wait1Msec(GATE_MOVE_MS);
  motor[gateMotor] = 0;
}

int readCompassCode() {
  return (SensorValue[compassMSB] << 3) +
         (SensorValue[compassBit2] << 2) +
         (SensorValue[compassBit1] << 1) +
         SensorValue[compassLSB];
}

int compassCodeToIndex(int code) {
  switch (code) {
    case 14: return 0; // N
    case 12: return 1; // NE
    case 13: return 2; // E
    case 9:  return 3; // SE
    case 11: return 4; // S
    case 3:  return 5; // SW
    case 7:  return 6; // W
    case 6:  return 7; // NW
    default: return -1;
  }
}

string headingFromIndex(int index) {
  switch (index) {
    case 0: return "N";
    case 1: return "NE";
    case 2: return "E";
    case 3: return "SE";
    case 4: return "S";
    case 5: return "SW";
    case 6: return "W";
    case 7: return "NW";
    default: return "UNKNOWN";
  }
}

int readCompassIndex() {
  return compassCodeToIndex(readCompassCode());
}

int alignToHeading(int targetHeading, int timeoutMs) {
  int startTime = nSysTime;

  while ((nSysTime - startTime) < timeoutMs) {
    int currentHeading = readCompassIndex();
    if (currentHeading == targetHeading) {
      stopDrive();
      return 1;
    }

    if (currentHeading < 0) {
      rotateCW(ALIGN_TURN_POWER);
      wait1Msec(80);
      continue;
    }

    // Shortest turn on 8-direction compass ring.
    int cwSteps = (targetHeading - currentHeading + 8) % 8;
    if (cwSteps <= 4) {
      rotateCW(ALIGN_TURN_POWER);
    } else {
      rotateCCW(ALIGN_TURN_POWER);
    }
    wait1Msec(70);
  }

  stopDrive();
  return 0;
}

int reverseToCollection(int timeoutMs) {
  int startTime = nSysTime;

  while ((nSysTime - startTime) < timeoutMs) {
    int bl = SensorValue[backLeftLine];
    int br = SensorValue[backRightLine];
    int backNear = (SensorValue[backLight] >= BACK_COLLECTION_NEAR_MIN);

    if (bl && br && backNear) {
      stopDrive();
      return 1;
    }

    if (bl && !br) {
      // Left side already close to line; bias to the right.
      setDrive(-REVERSE_CORRECT_POWER, -REVERSE_POWER);
    } else if (br && !bl) {
      // Right side already close to line; bias to the left.
      setDrive(-REVERSE_POWER, -REVERSE_CORRECT_POWER);
    } else {
      setDrive(-REVERSE_POWER, -REVERSE_POWER);
    }

    wait1Msec(30);
  }

  stopDrive();
  return 0;
}

int runBallDepositRoutine() {
  int aligned = alignToHeading(HEADING_NORTH, 4500);
  if (!aligned) {
    writeDebugStreamLine("Deposit: failed to align North.");
    return 0;
  }

  writeDebugStreamLine("Deposit: aligned North.");
  writeDebugStreamLine("Heading now: %s", headingFromIndex(readCompassIndex()));

  if (!reverseToCollection(7000)) {
    writeDebugStreamLine("Deposit: failed to reach collection zone.");
    return 0;
  }

  stopDrive();
  writeDebugStreamLine("Deposit: reached collection zone. Opening gate...");
  openGate();
  wait1Msec(250);
  closeGate();

  // Move forward slightly after drop to clear the wall.
  setDrive(65, 65);
  wait1Msec(350);
  stopDrive();

  return 1;
}

task main() {
  clearDebugStream();
  writeDebugStreamLine("Ball deposit test started.");

  while (true) {
    int centerReady = (SensorValue[centerLight] >= CENTER_BALL_INSIDE_MIN);
    writeDebugStreamLine("Center sensor says ball loaded: %d", centerReady);

    if (runBallDepositRoutine()) {
      writeDebugStreamLine("Result: DEPOSIT SUCCESS.");
    } else {
      writeDebugStreamLine("Result: DEPOSIT FAILED OR TIMEOUT.");
    }

    wait1Msec(1500);
  }
}
