#pragma config(Sensor, in4,    frontBelowLight, sensorAnalog)
#pragma config(Sensor, in3,    frontUpperLight, sensorAnalog)
#pragma config(Sensor, in2,    centerLight,     sensorAnalog)
#pragma config(Sensor, in1,    backLight,       sensorAnalog)
#pragma config(Sensor, dgtl12,  frontLeftLine,   sensorDigitalIn)
#pragma config(Sensor, dgtl11,  frontRightLine,  sensorDigitalIn)
#pragma config(Sensor, dgtl10,  backLeftLine,    sensorDigitalIn)
#pragma config(Sensor, dgtl9,  backRightLine,   sensorDigitalIn)
#pragma config(Sensor, dgtl1,  unusedD1,        sensorNone)
#pragma config(Sensor, dgtl2,  unusedD2,        sensorNone)
#pragma config(Sensor, dgtl7,  unusedD7,        sensorNone)
#pragma config(Sensor, dgtl8,  unusedD8,        sensorNone)
#pragma config(Sensor, dgtl3,  west,      sensorDigitalIn)
#pragma config(Sensor, dgtl4,  south,     sensorDigitalIn)
#pragma config(Sensor, dgtl5,  east,     sensorDigitalIn)
#pragma config(Sensor, dgtl6,  noth,      sensorDigitalIn)
#pragma config(Motor,  port6,           gateMotor,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           collectorMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftWheel,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightWheel,    tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



/*
  boundary_check_test.c
  Roomba-style boundary behavior:
  move forward -> detect line -> reverse and turn -> continue forward.
*/

const int FORWARD_POWER = 53;
const int BOUNDARY_REVERSE_POWER = 53;
const int BOUNDARY_REVERSE_MS = 1500;
const int BOUNDARY_ALIGN_TURN_POWER = 55;

void setDrive(int leftPower, int rightPower) {
  motor[leftWheel] = leftPower;
  motor[rightWheel] = rightPower;
}

void stopDrive() {
  setDrive(0, 0);
}

void turnLeftInPlace(int power) {
  setDrive(-power, power);
}

void turnRightInPlace(int power) {
  setDrive(power, -power);
}

int readCompassDirectionIndex() {
  // Compass outputs are active-low: 0 means that direction is active.
  if (SensorValue[noth] == 0) return 0; // N
  if (SensorValue[east] == 0) return 1; // E
  if (SensorValue[south] == 0) return 2; // S
  if (SensorValue[west] == 0) return 3; // W
  return -1;
}

int anyLineDetected() {
  return (SensorValue[frontLeftLine] == 0 ||
          SensorValue[frontRightLine] == 0 ||
          SensorValue[backLeftLine] == 0 ||
          SensorValue[backRightLine] == 0);
}

void recoverFromBoundary() {
  int currentHeading = -1;

  // Requested behavior: reverse first to clear the corner before rotating.
  setDrive(-BOUNDARY_REVERSE_POWER, -BOUNDARY_REVERSE_POWER);
  wait1Msec(BOUNDARY_REVERSE_MS);

  while (true) {
    if (SensorValue[west] == 0) {
      break;
    }

    currentHeading = readCompassDirectionIndex();
    if (currentHeading < 0) {
      turnRightInPlace(BOUNDARY_ALIGN_TURN_POWER);
      wait1Msec(40);
      continue;
    } else if (currentHeading == 3) {
      break;
    } else {
      // Simple constant rotation until WEST is detected.
      turnRightInPlace(BOUNDARY_ALIGN_TURN_POWER);
    }

    wait1Msec(40);
  }

  stopDrive();
  wait1Msec(100);
}

task main() {
  clearDebugStream();
  writeDebugStreamLine("Boundary check test started.");

  while (true) {
    if (anyLineDetected()) {
      writeDebugStreamLine(
        "Boundary hit FL=%d FR=%d BL=%d BR=%d",
        SensorValue[frontLeftLine],
        SensorValue[frontRightLine],
        SensorValue[backLeftLine],
        SensorValue[backRightLine]
      );
      recoverFromBoundary();
    } else {
      setDrive(FORWARD_POWER, FORWARD_POWER);
    }

    wait1Msec(25);
  }
}
