#pragma config(Sensor, in5,    centerLight,    sensorAnalog)
#pragma config(Sensor, in6,    backLight,      sensorAnalog)
#pragma config(Sensor, in7,    frontUpperLight, sensorAnalog)
#pragma config(Sensor, in8,    frontBelowLight, sensorAnalog)
#pragma config(Sensor, dgtl1,  unusedD1,       sensorNone)
#pragma config(Sensor, dgtl2,  unusedD2,       sensorNone)
#pragma config(Sensor, dgtl3,  west,           sensorDigitalIn)
#pragma config(Sensor, dgtl4,  south,          sensorDigitalIn)
#pragma config(Sensor, dgtl5,  east,           sensorDigitalIn)
#pragma config(Sensor, dgtl6,  north,           sensorDigitalIn)
#pragma config(Sensor, dgtl9,  backRightLine,         sensorDigitalIn)
#pragma config(Sensor, dgtl10, backLeftLine,          sensorDigitalIn)
#pragma config(Sensor, dgtl11, frontRightLine,            sensorDigitalIn)
#pragma config(Sensor, dgtl12, frontLeftLine,            sensorDigitalIn)
#pragma config(Motor,  port6,           gateMotor,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           collectorMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightWheel,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftWheel,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/*
  boundary_check_test.c
  Random heading stress test for boundary recovery:
  random rotate -> move forward until boundary -> recover -> repeat.
*/

const int FORWARD_POWER = 53;
const int RANDOM_TURN_POWER = 55;
const int ALIGN_TURN_POWER = 40;
const int RECOVERY_POWER = 53;

const int FRONT_RECOVERY_MS = 1000;
const int BACK_RECOVERY_MS = 1000;
const int RANDOM_TURN_MIN_MS = 350;
const int RANDOM_TURN_MAX_MS = 1300;

const int floorValue = 0;
const int boundaryValue = 1;

const int TRIGGER_NONE = 0;
const int TRIGGER_FRONT = 1;
const int TRIGGER_BACK = 2;
const int TRIGGER_BOTH = 3;

void setDrive(int leftPower, int rightPower) {
  motor[leftWheel] = leftPower;
  motor[rightWheel] = rightPower;
}

void stopDrive() {
  setDrive(0, 0);
}

void turnLeftInPlace(int power) {
  setDrive(-power, power);
}

void turnRightInPlace(int power) {
  setDrive(power, -power);
}

void driveForward(int power) {
  setDrive(power, power);
}

void driveBackward(int power) {
  setDrive(-power, -power);
}

int isBoundaryLine(int sensorValue) {
  return (sensorValue == boundaryValue);
}

int frontBoundaryDetected() {
  return (isBoundaryLine(SensorValue[frontLeftLine]) ||
          isBoundaryLine(SensorValue[frontRightLine]));
}

int backBoundaryDetected() {
  return (isBoundaryLine(SensorValue[backLeftLine]) ||
          isBoundaryLine(SensorValue[backRightLine]));
}

int detectBoundaryTrigger() {
  int frontTriggered = frontBoundaryDetected();
  int backTriggered = backBoundaryDetected();

  if (frontTriggered && backTriggered) return TRIGGER_BOTH;
  if (frontTriggered) return TRIGGER_FRONT;
  if (backTriggered) return TRIGGER_BACK;can ouy 
  return TRIGGER_NONE;
}

int isEastAlignedExact() {
  return (SensorValue[east] == 0 &&
          SensorValue[north] == 1 &&
          SensorValue[south] == 1 &&
          SensorValue[west] == 1);
}

void alignToEast() {
  int stableCount = 0;
  const int REQUIRED_STABLE_SAMPLES = 3;

  // Keep turning until east is active and all other directions are inactive.
  while (stableCount < REQUIRED_STABLE_SAMPLES) {
    if (isEastAlignedExact()) {
      stableCount++;
      stopDrive();
      wait1Msec(20);
      continue;
    }

    stableCount = 0;
    turnRightInPlace(ALIGN_TURN_POWER);
    wait1Msec(25);
  }

  stopDrive();
  wait1Msec(100);
}

void doRandomRotation() {
  int turnDir = random(2); // 0 = left, 1 = right
  int turnMs = RANDOM_TURN_MIN_MS + random(RANDOM_TURN_MAX_MS - RANDOM_TURN_MIN_MS + 1);

  if (turnDir == 0) {
    turnLeftInPlace(RANDOM_TURN_POWER);
  } else {
    turnRightInPlace(RANDOM_TURN_POWER);
  }

  wait1Msec(turnMs);
  stopDrive();
  wait1Msec(100);
}

void recoverFromBoundary(int triggerSource) {
  // Recovery must be pure straight motion only.
  stopDrive();
  wait1Msec(40);

  if (triggerSource == TRIGGER_BACK) {
    // Back line triggered: pure forward recovery.
    driveForward(RECOVERY_POWER);
    wait1Msec(BACK_RECOVERY_MS);
  } else {
    // Front line (or both) triggered: pure backward recovery.
    driveBackward(RECOVERY_POWER);
    wait1Msec(FRONT_RECOVERY_MS);
  }

  // Stop first, then do heading alignment to EAST.
  stopDrive();
  wait1Msec(80);
  alignToEast();
}

task main() {
  clearDebugStream();
  writeDebugStreamLine("Boundary check test started.");
  writeDebugStreamLine("floorValue=%d boundaryValue=%d", floorValue, boundaryValue);

  while (true) {
    int trigger = TRIGGER_NONE;

    doRandomRotation();

    // Keep moving forward until any boundary sensor is triggered.
    while (trigger == TRIGGER_NONE) {
      driveForward(FORWARD_POWER);
      trigger = detectBoundaryTrigger();
      wait1Msec(20);
    }

    writeDebugStreamLine(
      "Boundary trigger=%d FL=%d FR=%d BL=%d BR=%d",
      trigger,
      SensorValue[frontLeftLine],
      SensorValue[frontRightLine],
      SensorValue[backLeftLine],
      SensorValue[backRightLine]
    );
    recoverFromBoundary(trigger);
  }
}
