#pragma config(Sensor, in5,    centerLight,    sensorAnalog)
#pragma config(Sensor, in6,    backLight,      sensorAnalog)
#pragma config(Sensor, in7,    frontUpperLight, sensorAnalog)
#pragma config(Sensor, in8,    frontBelowLight, sensorAnalog)
#pragma config(Sensor, dgtl1,  unusedD1,       sensorNone)
#pragma config(Sensor, dgtl2,  unusedD2,       sensorNone)
#pragma config(Sensor, dgtl3,  west,           sensorDigitalIn)
#pragma config(Sensor, dgtl4,  south,          sensorDigitalIn)
#pragma config(Sensor, dgtl5,  east,           sensorDigitalIn)
#pragma config(Sensor, dgtl6,  north,           sensorDigitalIn)
#pragma config(Sensor, dgtl9,  backRightLine,         sensorDigitalIn)
#pragma config(Sensor, dgtl10, backLeftLine,          sensorDigitalIn)
#pragma config(Sensor, dgtl11, frontRightLine,            sensorDigitalIn)
#pragma config(Sensor, dgtl12, frontLeftLine,            sensorDigitalIn)
#pragma config(Motor,  port6,           gateMotor,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           collectorMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightWheel,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftWheel,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int CENTER_BALL_COLLECT_MIN = 1300;
const int COLLECT_TIMEOUT_MS = 1000;
const int COLLECT_EXTRA_SPIN_TIMEOUT_MS = 5000;
const int DRIVE_COLLECT_POWER = 90;
const int COLLECTOR_POWER = 200;

const int COLLECT_RESULT_TIMEOUT = 0;
const int COLLECT_RESULT_SUCCESS = 1;

void setDrive(int leftPower, int rightPower) {
  motor[leftWheel] = leftPower;
  motor[rightWheel] = rightPower;
}

void stopDrive() {
  setDrive(0, 0);
}

void setStatusLeds(int yellowOn, int greenOn, int redOn) {
  SensorValue[yellow] = yellowOn;
  SensorValue[green] = greenOn;
  SensorValue[red] = redOn;
}

int isBallCollectedAtCenter() {
  return SensorValue[centerLight] > CENTER_BALL_COLLECT_MIN;
}

int runCollectingPhase() {
  int startTime = nSysTime;
  writeDebugStreamLine("COLLECTING started.");
  setStatusLeds(0, 0, 0);

  if (isBallCollectedAtCenter()) {
    stopDrive();
    setStatusLeds(0, 1, 0);
    writeDebugStreamLine("COLLECTING immediate success (ball already at center).");
    return COLLECT_RESULT_SUCCESS;
  }

  while ((nSysTime - startTime) < COLLECT_TIMEOUT_MS) {
    if (isBallCollectedAtCenter()) {
      stopDrive();
      setStatusLeds(0, 1, 0);
      writeDebugStreamLine("COLLECTING success before timeout.");
      return COLLECT_RESULT_SUCCESS;
    }

    setDrive(DRIVE_COLLECT_POWER, DRIVE_COLLECT_POWER);
    setStatusLeds(1, 0, 0);
    wait1Msec(20);
  }

  stopDrive();
  setStatusLeds(0, 0, 0);
  writeDebugStreamLine("COLLECTING forward timeout (1s). Extra collector spin starts.");

  startTime = nSysTime;
  motor[collectorMotor] = COLLECTOR_POWER; // Keep collector spinning while wheels are stopped.
  while ((nSysTime - startTime) < COLLECT_EXTRA_SPIN_TIMEOUT_MS) {
    if (isBallCollectedAtCenter()) {
      stopDrive();
      setStatusLeds(0, 1, 0);
      writeDebugStreamLine("COLLECTING success during extra collector spin.");
      return COLLECT_RESULT_SUCCESS;
    }
    wait1Msec(20);
  }

  setStatusLeds(0, 0, 1);
  writeDebugStreamLine("COLLECTING timeout after extra 5s collector spin.");
  return COLLECT_RESULT_TIMEOUT;
}

task main() {
  int collectResult;

  clearDebugStream();
  writeDebugStreamLine("Standalone COLLECTING phase started (one-shot).");
  setStatusLeds(0, 0, 0);
  motor[collectorMotor] = COLLECTOR_POWER;

  collectResult = runCollectingPhase();

  stopDrive();
  motor[collectorMotor] = 0;
  writeDebugStreamLine(
    "Standalone COLLECTING finished. Result = %d (1=success, 0=timeout)",
    collectResult
  );
}
