/*
  depositing_phase.c
  Standalone DEPOSITING phase logic.
*/

#pragma config(Sensor, in5,    centerLight,    sensorAnalog)
#pragma config(Sensor, in6,    backLight,      sensorAnalog)
#pragma config(Sensor, in7,    frontUpperLight, sensorAnalog)
#pragma config(Sensor, in8,    frontBelowLight, sensorAnalog)
#pragma config(Sensor, dgtl1,  unusedD1,       sensorNone)
#pragma config(Sensor, dgtl2,  unusedD2,       sensorNone)
#pragma config(Sensor, dgtl3,  west,           sensorDigitalIn)
#pragma config(Sensor, dgtl4,  south,          sensorDigitalIn)
#pragma config(Sensor, dgtl5,  east,           sensorDigitalIn)
#pragma config(Sensor, dgtl6,  noth,           sensorDigitalIn)
#pragma config(Sensor, dgtl7,  unusedD7,       sensorNone)
#pragma config(Sensor, dgtl8,  unusedD8,       sensorNone)
#pragma config(Sensor, dgtl9,  yellow,         sensorDigitalOut)
#pragma config(Sensor, dgtl10, green,          sensorDigitalOut)
#pragma config(Sensor, dgtl11, red,            sensorDigitalOut)
#pragma config(Motor,  port6,           gateMotor,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           collectorMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightWheel,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftWheel,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int BACK_STABLE_FLUCT_LIMIT = 300;
const int DEPOSIT_ALIGN_TIMEOUT_MS = 5000;
const int DEPOSIT_INITIAL_REVERSE_MS = 4000;
const int DEPOSIT_STEP_REVERSE_MS = 1000;
const int DEPOSIT_TIMEOUT_MS = 10000;
const int DEPOSIT_STABILITY_SAMPLE_MS = 400;
const int DEPOSIT_SETTLE_MS = 120;
const int DRIVE_REVERSE_POWER = 80;
const int DRIVE_TURN_POWER = 60;

const int DEPOSIT_RESULT_TIMEOUT = 0;
const int DEPOSIT_RESULT_STABLE = 1;

void setDrive(int leftPower, int rightPower) {
  motor[leftWheel] = leftPower;
  motor[rightWheel] = rightPower;
}

void stopDrive() {
  setDrive(0, 0);
}

void turnLeftInPlace(int power) {
  setDrive(-power, power);
}

int isFacingWest() {
  return (SensorValue[west] == 0 &&
          SensorValue[south] == 1 &&
          SensorValue[east] == 1 &&
          SensorValue[noth] == 1);
}

void alignToWestCCW(int timeoutMs) {
  int startTime = nSysTime;

  while ((nSysTime - startTime) < timeoutMs && !isFacingWest()) {
    turnLeftInPlace(DRIVE_TURN_POWER);
    wait1Msec(20);
  }

  stopDrive();
}

void reverseKeepingWest(int durationMs) {
  int startTime = nSysTime;

  while ((nSysTime - startTime) < durationMs) {
    if (isFacingWest()) {
      setDrive(-DRIVE_REVERSE_POWER, -DRIVE_REVERSE_POWER);
    } else {
      turnLeftInPlace(DRIVE_TURN_POWER);
    }

    wait1Msec(20);
  }

  stopDrive();
}

int measureBackSensorFluctuation(int sampleMs) {
  int startTime = nSysTime;
  int minVal = 4095;
  int maxVal = 0;
  int value = 0;

  while ((nSysTime - startTime) < sampleMs) {
    value = SensorValue[backLight];
    if (value < minVal) minVal = value;
    if (value > maxVal) maxVal = value;
    wait1Msec(20);
  }

  return (maxVal - minVal);
}

int checkBackStabilityAfterCycle() {
  // Sample only after reverse motion has fully stopped.
  stopDrive();
  wait1Msec(DEPOSIT_SETTLE_MS);
  return measureBackSensorFluctuation(DEPOSIT_STABILITY_SAMPLE_MS);
}

int runDepositingPhase() {
  int phaseStart = nSysTime;
  int fluctuation = 0;
  int depositCycle = 1;

  writeDebugStreamLine("DEPOSITING started.");
  alignToWestCCW(DEPOSIT_ALIGN_TIMEOUT_MS);
  reverseKeepingWest(DEPOSIT_INITIAL_REVERSE_MS);

  while ((nSysTime - phaseStart) < DEPOSIT_TIMEOUT_MS) {
    fluctuation = checkBackStabilityAfterCycle();
    writeDebugStreamLine(
      "DEPOSIT cycle %d check: back fluctuation = %d",
      depositCycle,
      fluctuation
    );

    if (fluctuation <= BACK_STABLE_FLUCT_LIMIT) {
      writeDebugStreamLine("DEPOSIT complete: back sensor is stable.");
      return DEPOSIT_RESULT_STABLE;
    }

    alignToWestCCW(DEPOSIT_ALIGN_TIMEOUT_MS);
    reverseKeepingWest(DEPOSIT_STEP_REVERSE_MS);
    depositCycle++;
  }

  stopDrive();
  writeDebugStreamLine("DEPOSIT timeout (10s).");
  return DEPOSIT_RESULT_TIMEOUT;
}

task main() {
  int depositResult;

  clearDebugStream();
  writeDebugStreamLine("Standalone DEPOSITING phase started (one-shot).");

  depositResult = runDepositingPhase();

  stopDrive();
  writeDebugStreamLine(
    "Standalone DEPOSITING finished. Result = %d (1=stable, 0=timeout)",
    depositResult
  );
}
