#pragma config(Sensor, in5,    centerLight,      sensorAnalog)
#pragma config(Sensor, in6,    backLight,        sensorAnalog)
#pragma config(Sensor, in7,    frontUpperLight,  sensorAnalog)
#pragma config(Sensor, in8,    frontBelowLight,  sensorAnalog)
#pragma config(Sensor, dgtl1,  unusedD1,         sensorNone)
#pragma config(Sensor, dgtl2,  unusedD2,         sensorNone)
#pragma config(Sensor, dgtl3,  west,             sensorDigitalIn)
#pragma config(Sensor, dgtl4,  south,            sensorDigitalIn)
#pragma config(Sensor, dgtl5,  east,             sensorDigitalIn)
#pragma config(Sensor, dgtl6,  noth,             sensorDigitalIn)
#pragma config(Sensor, dgtl7,  unusedD7,         sensorNone)
#pragma config(Sensor, dgtl8,  unusedD8,         sensorNone)
#pragma config(Sensor, dgtl9,  yellow,           sensorDigitalOut)
#pragma config(Sensor, dgtl10, green,            sensorDigitalOut)
#pragma config(Sensor, dgtl11, red,              sensorDigitalOut)
#pragma config(Motor,  port6,           gateMotor,      tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           collectorMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightWheel,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftWheel,      tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int BACK_SENSOR_DONE_MIN = 2500;
const int DEPOSIT_ALIGN_TIMEOUT_MS = 5000;
const int DEPOSIT_INITIAL_REVERSE_MS = 3000;
const int DEPOSIT_STEP_REVERSE_MS = 1000;
const int DEPOSIT_TIMEOUT_MS = 10000;
const int DRIVE_REVERSE_LEFT_POWER = 80;
const int DRIVE_REVERSE_RIGHT_POWER = 60;
const int DRIVE_TURN_POWER = 60;

const int DEPOSIT_RESULT_TIMEOUT = 0;
const int DEPOSIT_RESULT_STABLE = 1;

int depositSequenceHasRun = 0;

void setDrive(int leftPower, int rightPower) {
  motor[leftWheel] = leftPower;
  motor[rightWheel] = rightPower;
}

void stopDrive() {
  setDrive(0, 0);
}

void setStatusLeds(int yellowOn, int greenOn, int redOn) {
  SensorValue[yellow] = yellowOn;
  SensorValue[green] = greenOn;
  SensorValue[red] = redOn;
}

void turnLeftInPlace(int power) {
  setDrive(-power, power);
}

int isFacingEast() {
  return (SensorValue[west] == 1 &&
          SensorValue[south] == 1 &&
          SensorValue[east] == 0 &&
          SensorValue[noth] == 1);
}

void alignToEastCCW(int timeoutMs) {
  int startTime = nSysTime;

  while ((nSysTime - startTime) < timeoutMs && !isFacingEast()) {
    turnLeftInPlace(DRIVE_TURN_POWER);
    wait1Msec(20);
  }

  stopDrive();
}

void reverseStraightForMs(int durationMs) {
  int startTime = nSysTime;

  while ((nSysTime - startTime) < durationMs) {
    setDrive(-DRIVE_REVERSE_LEFT_POWER, -DRIVE_REVERSE_RIGHT_POWER);
    wait1Msec(20);
  }

  stopDrive();
}

int isDepositCompleteNow() {
  int backValue = SensorValue[backLight];
  int facingEast = isFacingEast();
  return (backValue > BACK_SENSOR_DONE_MIN && facingEast);
}

int runDepositingPhase() {
  int phaseStart = nSysTime;
  int backValue = 0;
  int facingEast = 0;
  int depositCycle = 1;

  if (depositSequenceHasRun) {
    stopDrive();
    setStatusLeds(0, 0, 1);
    writeDebugStreamLine("DEPOSIT sequence already executed once. Skipping re-run.");
    return DEPOSIT_RESULT_TIMEOUT;
  }

  depositSequenceHasRun = 1;
  setStatusLeds(1, 0, 0); // yellow ON while deposit sequence is running
  writeDebugStreamLine("DEPOSITING started.");
  alignToEastCCW(DEPOSIT_ALIGN_TIMEOUT_MS);
  reverseStraightForMs(DEPOSIT_INITIAL_REVERSE_MS);

  while ((nSysTime - phaseStart) < DEPOSIT_TIMEOUT_MS) {
    backValue = SensorValue[backLight];
    facingEast = isFacingEast();
    writeDebugStreamLine(
      "DEPOSIT cycle %d check: back=%d facingEast=%d",
      depositCycle,
      backValue,
      facingEast
    );

    if (isDepositCompleteNow()) {
      setStatusLeds(0, 1, 0);
      writeDebugStreamLine("DEPOSIT complete: back>2500 and EAST aligned.");
      return DEPOSIT_RESULT_STABLE;
    }

    if (!facingEast) {
      writeDebugStreamLine("DEPOSIT cycle %d: heading drifted, re-aligning to EAST.", depositCycle);
      alignToEastCCW(DEPOSIT_ALIGN_TIMEOUT_MS);
    }

    reverseStraightForMs(DEPOSIT_STEP_REVERSE_MS);
    depositCycle++;
  }

  stopDrive();
  setStatusLeds(0, 0, 1);
  writeDebugStreamLine("DEPOSIT timeout (10s).");
  return DEPOSIT_RESULT_TIMEOUT;
}

task main() {
  int depositResult;

  clearDebugStream();
  writeDebugStreamLine("Standalone DEPOSITING phase started (one-shot).");
  setStatusLeds(0, 0, 0);

  depositResult = runDepositingPhase();

  stopDrive();
  writeDebugStreamLine(
    "Standalone DEPOSITING finished. Result = %d (1=stable, 0=timeout)",
    depositResult
  );
}
