#pragma config(Sensor, in8,    frontBelowLight, sensorAnalog)
#pragma config(Sensor, in7,    frontUpperLight, sensorAnalog)
#pragma config(Sensor, in5,    centerLight,     sensorAnalog)
#pragma config(Sensor, in6,    backLight,       sensorAnalog)
#pragma config(Sensor, dgtl12, frontLeftLine,   sensorDigitalIn)
#pragma config(Sensor, dgtl11, frontRightLine,  sensorDigitalIn)
#pragma config(Sensor, dgtl10, backLeftLine,    sensorDigitalIn)
#pragma config(Sensor, dgtl9,  backRightLine,   sensorDigitalIn)
#pragma config(Sensor, dgtl1,  unusedD1,        sensorNone)
#pragma config(Sensor, dgtl2,  unusedD2,        sensorNone)
#pragma config(Sensor, dgtl7,  unusedD7,        sensorNone)
#pragma config(Sensor, dgtl8,  unusedD8,        sensorNone)
#pragma config(Sensor, dgtl3,  west,            sensorDigitalIn)
#pragma config(Sensor, dgtl4,  south,           sensorDigitalIn)
#pragma config(Sensor, dgtl5,  east,            sensorDigitalIn)
#pragma config(Sensor, dgtl6,  noth,            sensorDigitalIn)
#pragma config(Motor,  port6,  gateMotor,       tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,  collectorMotor,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,  rightWheel,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,  leftWheel,       tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  robot_search_east_loop.c

  Behavior:
  1) Move forward for 1.0 second while checking frontBelowLight for a ball.
     - If ball detected, stop permanently.
  2) Rotate CCW until facing EAST while still checking frontBelowLight.
     - If ball detected, stop permanently.
  3) If no ball found, align to EAST again.
  4) Move forward for 0.5 second while checking frontBelowLight.
     - If ball detected, stop permanently.
  5) Rotate CCW until facing EAST while still checking frontBelowLight.
     - If ball detected, stop permanently.
  6) Repeat steps 3-5 forever.
*/

const int FRONT_LOWER_BALL_MIN = 800;

const int DRIVE_FORWARD_POWER = 85;
const int DRIVE_TURN_POWER = 40;

const int FIRST_FORWARD_MS = 1000;
const int REPEAT_FORWARD_MS = 500;
const int ALIGN_TIMEOUT_MS = 60000;
const int LOOP_DELAY_MS = 20;
const int COMPASS_SETTLE_MS = 80;

void setDrive(int leftPower, int rightPower) {
  motor[leftWheel] = leftPower;
  motor[rightWheel] = rightPower;
}

void stopDrive() {
  setDrive(0, 0);
}

void turnLeftInPlace(int power) {
  setDrive(-power, power);
}

int isBallDetectedFrontBelow() {
  return SensorValue[frontBelowLight] > FRONT_LOWER_BALL_MIN;
}

int isFacingEast() {
  return (SensorValue[east] == 0 &&
          SensorValue[west] == 1 &&
          SensorValue[south] == 1 &&
          SensorValue[noth] == 1);
}

void stopForeverBecauseBallFound() {
  stopDrive();
  writeDebugStreamLine("BALL FOUND. Robot stopped.");
  while (true) {
    stopDrive();
    wait1Msec(50);
  }
}

void checkBallAndStopIfFound() {
  if (isBallDetectedFrontBelow()) {
    stopForeverBecauseBallFound();
  }
}

void driveForwardForMsAndStopIfBallFound(int durationMs) {
  int startTime = nSysTime;

  while ((nSysTime - startTime) < durationMs) {
    checkBallAndStopIfFound();
    setDrive(DRIVE_FORWARD_POWER, DRIVE_FORWARD_POWER);
    wait1Msec(LOOP_DELAY_MS);
  }

  stopDrive();
}

void rotateCCWToEastAndStopIfBallFound(int timeoutMs) {
  int startTime = nSysTime;

  while ((nSysTime - startTime) < timeoutMs) {
    checkBallAndStopIfFound();

    if (isFacingEast()) {
      stopDrive();
      return;
    }

    turnLeftInPlace(DRIVE_TURN_POWER);
    wait1Msec(LOOP_DELAY_MS);
  }

  stopDrive();
}

void alignToEastCCW(int timeoutMs) {
  int startTime = nSysTime;

  while ((nSysTime - startTime) < timeoutMs && !isFacingEast()) {
    turnLeftInPlace(DRIVE_TURN_POWER);
    wait1Msec(LOOP_DELAY_MS);
  }

  stopDrive();
}

task main() {
  clearDebugStream();
  writeDebugStreamLine("Starting search routine.");

  // First forward movement: 1 second
  writeDebugStreamLine("Initial forward for 1.0 second.");
  driveForwardForMsAndStopIfBallFound(FIRST_FORWARD_MS);

  wait1Msec(COMPASS_SETTLE_MS);

  // First CCW rotation to East
  writeDebugStreamLine("Rotate CCW until facing EAST.");
  rotateCCWToEastAndStopIfBallFound(ALIGN_TIMEOUT_MS);

  wait1Msec(COMPASS_SETTLE_MS);

  // Repeat forever: align East -> forward 0.5 s -> rotate CCW to East
  while (true) {
    writeDebugStreamLine("Aligning to EAST before next forward step.");
    alignToEastCCW(ALIGN_TIMEOUT_MS);

    wait1Msec(COMPASS_SETTLE_MS);

    writeDebugStreamLine("Forward for 0.5 second.");
    driveForwardForMsAndStopIfBallFound(REPEAT_FORWARD_MS);

    wait1Msec(COMPASS_SETTLE_MS);

    writeDebugStreamLine("Rotate CCW until facing EAST.");
    rotateCCWToEastAndStopIfBallFound(ALIGN_TIMEOUT_MS);

    wait1Msec(COMPASS_SETTLE_MS);
  }
}
