#pragma config(Sensor, in5,    centerLight,     sensorAnalog)
#pragma config(Sensor, in6,    backLight,       sensorAnalog)
#pragma config(Sensor, in7,    frontUpperLight, sensorAnalog)
#pragma config(Sensor, in8,    frontBelowLight, sensorAnalog)
#pragma config(Sensor, dgtl1,  unusedD1,        sensorNone)
#pragma config(Sensor, dgtl2,  unusedD2,        sensorNone)
#pragma config(Sensor, dgtl3,  west,            sensorDigitalIn)
#pragma config(Sensor, dgtl4,  south,           sensorDigitalIn)
#pragma config(Sensor, dgtl5,  east,            sensorDigitalIn)
#pragma config(Sensor, dgtl6,  noth,            sensorDigitalIn)
#pragma config(Sensor, dgtl7,  unusedD7,        sensorNone)
#pragma config(Sensor, dgtl8,  unusedD8,        sensorNone)
#pragma config(Sensor, dgtl9,  yellow,          sensorDigitalOut)
#pragma config(Sensor, dgtl10, green,           sensorDigitalOut)
#pragma config(Sensor, dgtl11, red,             sensorDigitalOut)
#pragma config(Motor,  port6,  gateMotor,       tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,  collectorMotor,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,  rightWheel,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,  leftWheel,       tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  search_and_collect.c
  Runs the searching phase followed by the collecting phase in sequence.
  Phase logic lives in searching_phase.h and collecting_phase.h;
  shared motor/LED helpers are defined here so both headers can call them.
*/

// ── Collector power during the search approach (lower to avoid disturbing ball position)
const int SEARCH_COLLECTOR_POWER = 127;

// ── Shared drive helpers (used by both included headers) ─────────────────────
void setDrive(int leftPower, int rightPower) {
  motor[leftWheel]  = leftPower;
  motor[rightWheel] = rightPower;
}

void stopDrive() {
  setDrive(0, 0);
}

void turnLeftInPlace(int power) {
  setDrive(-power, power);
}

void reverseStraight(int power) {
  setDrive(-power, -power);
}

// ── LED helpers (searching_phase.h uses setDebugLeds; collecting_phase.h uses setStatusLeds)
void setDebugLeds(int yellowOn, int redOn, int greenOn) {
  SensorValue[yellow] = yellowOn;
  SensorValue[red]    = redOn;
  SensorValue[green]  = greenOn;
}

void setStatusLeds(int yellowOn, int greenOn, int redOn) {
  SensorValue[yellow] = yellowOn;
  SensorValue[green]  = greenOn;
  SensorValue[red]    = redOn;
}

// ── Phase logic ──────────────────────────────────────────────────────────────
#include "searching_phase.h"
#include "collecting_phase.h"

// ── Entry point ──────────────────────────────────────────────────────────────
task main() {
  int searchResult;
  int collectResult;

  clearDebugStream();
  writeDebugStreamLine("Search-and-collect sequence started.");
  setDebugLeds(0, 0, 0);
  motor[collectorMotor] = SEARCH_COLLECTOR_POWER;

  searchResult = runSearchingPhase();

  if (searchResult == SEARCH_RESULT_BALL_FOUND) {
    writeDebugStreamLine("Ball found — starting collecting phase.");
    motor[collectorMotor] = COLLECT_COLLECTOR_POWER;
    collectResult = runCollectingPhase();

    if (collectResult == COLLECT_RESULT_SUCCESS) {
      setStatusLeds(0, 1, 0);  // green: collected
      writeDebugStreamLine("Ball collected successfully.");
    } else {
      setStatusLeds(0, 0, 1);  // red: collect timed out
      writeDebugStreamLine("Collecting timed out.");
    }
  } else {
    setDebugLeds(0, 1, 0);  // red: no ball found
    writeDebugStreamLine("No ball found after all search cycles.");
  }

  stopDrive();
  motor[collectorMotor] = 0;
  writeDebugStreamLine("Search-and-collect sequence finished.");
}
